// SPDX-FileCopyrightText: Copyright (C) 2026 Thomas Steinke
// SPDX-License-Identifier: AGPL-3.0-or-later
package de.vvwt.tm.slotopt.e2e;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Test-support helper for TM slot-optimization end-to-end integration tests.
 *
 * <p>Provides DB fixture setup for large phases (lapCount {@literal >} 10 — above the exhaustive
 * routing threshold) and post-optimize assertion helpers.
 *
 * <h2>Large-phase construction</h2>
 *
 * <p>{@link #buildAndPersistLargePhase(UUID, JdbcTemplate)} inserts a tournament + phase with 12
 * teams in 1 group. Round-robin with N=12 teams in one group produces N−1=11 laps, which is one
 * above the {@code tm.slotopt.exhaustive-max-n=10} threshold — forcing Leg 2 or Leg 3 routing.
 * Matches are NOT inserted here; they are generated by the real {@code PhasePreparationService}
 * (via {@code generateMatches}) in the test after this method returns.
 *
 * <h2>Database isolation</h2>
 *
 * <p>Each test uses a dedicated H2 in-memory database (via the {@code spring.datasource.url}
 * property on the {@code @SpringBootTest} annotation) so there is no inter-test contamination.
 *
 * @see SlotOptE2EIT
 */
final class TmSlotOptE2ETestSupport {

    private TmSlotOptE2ETestSupport() {
        // utility class
    }

    /**
     * Inserts a tournament + phase with 12 teams in 1 group into the H2 in-memory database.
     *
     * <p>Round-robin with N=12 teams in 1 group produces N−1=11 laps after match generation — one
     * above the {@code tm.slotopt.exhaustive-max-n=10} threshold. This forces Leg 2 (dispatcher)
     * or Leg 3 (cancelable in-process) routing in {@code RoutingSlotOptimizationClient}.
     *
     * <p>The {@code locations} table entry is inserted with a random UUID. The tournament is in
     * {@code PLANNED} status with {@code field_count=2}, {@code team_count=12},
     * {@code optimize=true}. The phase is in {@code PREPARED} status.
     *
     * <p>Matches are NOT inserted — the caller must invoke {@code
     * PhasePreparationService.generateMatches(phaseId, "roundRobin")} to generate them. This
     * mirrors the real production pipeline (E55S04 OrchestratorHappyPathIT pattern).
     *
     * @param tournamentId the tournament UUID to use (caller supplies for traceability)
     * @param jdbcTemplate the JDBC template for the tenant-bound H2 database
     * @return the inserted phase UUID
     */
    static UUID buildAndPersistLargePhase(UUID tournamentId, JdbcTemplate jdbcTemplate) {
        UUID locationId = UUID.randomUUID();
        jdbcTemplate.update(
                "INSERT INTO locations (id, display_name) VALUES (?, ?)",
                locationId,
                "E63S08 E2E IT Location");

        // 12 teams / 1 group / 2 fields → 11 laps (N-1 for even N, round-robin) > threshold 10
        jdbcTemplate.update(
                "INSERT INTO tournament (id, location_id, description, match_format,"
                        + " scoring_rule_id, set_validation_rule_id, match_generator_id,"
                        + " status, created_at, field_count, team_count, optimize, draft_json)"
                        + " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                tournamentId,
                locationId,
                "E63S08 E2E IT Tournament",
                "BEST_OF_3",
                "setPoints",
                "standardVolleyball",
                "roundRobin",
                "PLANNED",
                LocalDateTime.now(),
                2, // field_count = 2
                12, // team_count = 12 → 11 laps in 1 group
                true,
                "{\"sections\": ["
                        + "  {\"sectionNumber\": 1, \"sortType\": \"team_number\","
                        + "   \"groupCount\": 1, \"gameMode\": \"roundRobin\","
                        + "   \"lapBreakTimeMinutes\": 0, \"sectionBreakTimeMinutes\": 0,"
                        + "   \"lapTimeMinutes\": 15, \"setQuantity\": 3, \"breaks\": []}"
                        + "]}");

        UUID phaseId = UUID.randomUUID();
        jdbcTemplate.update(
                "INSERT INTO phase (id, tournament_id, sequence_number, description,"
                        + " status, current_lap_number, created_at, optimized)"
                        + " VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                phaseId,
                tournamentId,
                1,
                "Phase 1",
                "PREPARED",
                0,
                LocalDateTime.now(),
                false);

        // 12 teams in 1 group (groupNumber=1, groupPosition=1..12)
        for (int i = 0; i < 12; i++) {
            UUID teamId = UUID.randomUUID();
            jdbcTemplate.update(
                    "INSERT INTO team (id, tournament_id, team_number, description, participate,"
                            + " created_at) VALUES (?, ?, ?, ?, ?, ?)",
                    teamId,
                    tournamentId,
                    i + 1,
                    "Team " + (i + 1),
                    true,
                    LocalDateTime.now());
            // team_avatar: groupNumber=1, groupPosition=i+1, team_id=NULL per DEC-59 Clause B
            jdbcTemplate.update(
                    "INSERT INTO team_avatar (id, tournament_id, phase_id, group_number,"
                            + " group_position, team_id) VALUES (?, ?, ?, ?, ?, NULL)",
                    UUID.randomUUID(),
                    tournamentId,
                    phaseId,
                    1,
                    i + 1);
        }

        return phaseId;
    }

    /**
     * Asserts that every match in the given phase has a non-null {@code lap_number} and a non-null
     * {@code field_number} after slot optimization completes.
     *
     * <p>This assertion covers AC-TEST-E2E-LEG2-LIVE-WORKER,
     * AC-TEST-E2E-EMBEDDED-WORKER-CONTRIBUTES, and AC-TEST-E2E-LEG3-FALLBACK: in all three legs
     * the postcondition is the same — every match has non-null slot coordinates.
     *
     * @param phaseId the phase to verify
     * @param jdbcTemplate the JDBC template for the tenant-bound H2 database
     */
    static void assertMatchesOptimized(UUID phaseId, JdbcTemplate jdbcTemplate) {
        int totalMatches =
                jdbcTemplate.queryForObject(
                        "SELECT COUNT(*) FROM match WHERE phase_id = ?",
                        Integer.class,
                        phaseId);
        assertThat(totalMatches)
                .as("phase %s must have at least 1 match after optimization", phaseId)
                .isGreaterThan(0);

        int nullLapCount =
                jdbcTemplate.queryForObject(
                        "SELECT COUNT(*) FROM match WHERE phase_id = ? AND lap_number IS NULL",
                        Integer.class,
                        phaseId);
        assertThat(nullLapCount)
                .as(
                        "all matches in phase %s must have a non-null lap_number after optimize()"
                                + " — found %d matches with null lap_number out of %d total",
                        phaseId, nullLapCount, totalMatches)
                .isZero();

        int nullFieldCount =
                jdbcTemplate.queryForObject(
                        "SELECT COUNT(*) FROM match WHERE phase_id = ? AND field_number IS NULL",
                        Integer.class,
                        phaseId);
        assertThat(nullFieldCount)
                .as(
                        "all matches in phase %s must have a non-null field_number after optimize()"
                                + " — found %d matches with null field_number out of %d total",
                        phaseId, nullFieldCount, totalMatches)
                .isZero();
    }

    /**
     * Deletes all test data for a tournament and its location from the H2 in-memory DB.
     *
     * <p>Disables referential integrity during deletion for simplicity (H2-compatible).
     *
     * @param tournamentId the tournament UUID whose data should be removed
     * @param jdbcTemplate the JDBC template for the tenant-bound H2 database
     */
    static void cleanUpTournament(UUID tournamentId, JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("SET REFERENTIAL_INTEGRITY FALSE");
        try {
            jdbcTemplate.update(
                    "DELETE FROM match WHERE phase_id IN"
                            + " (SELECT id FROM phase WHERE tournament_id = ?)",
                    tournamentId);
            jdbcTemplate.update("DELETE FROM team_avatar WHERE tournament_id = ?", tournamentId);
            jdbcTemplate.update("DELETE FROM team WHERE tournament_id = ?", tournamentId);
            jdbcTemplate.update("DELETE FROM phase WHERE tournament_id = ?", tournamentId);
            // Retrieve and delete location
            String locationId =
                    jdbcTemplate.queryForObject(
                            "SELECT CAST(location_id AS VARCHAR) FROM tournament WHERE id = ?",
                            String.class,
                            tournamentId);
            jdbcTemplate.update("DELETE FROM tournament WHERE id = ?", tournamentId);
            if (locationId != null) {
                jdbcTemplate.update("DELETE FROM locations WHERE id = ?", locationId);
            }
        } finally {
            jdbcTemplate.execute("SET REFERENTIAL_INTEGRITY TRUE");
        }
    }
}
