// SPDX-FileCopyrightText: Copyright (C) 2026 Thomas Steinke
// SPDX-License-Identifier: AGPL-3.0-or-later
package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Append-only tournament audit log entry — file-based persistence (E55S13, DEC-14 amendment
 * 2026-05-14).
 *
 * <p>Promoted to the public {@code tournament} package per DEC-35 §3 (entities pass module
 * boundaries as data-shaped types at the public surface — E31S01). The entity was previously in
 * {@code tournament.internal}.
 *
 * <p>Post-E55S13: persisted to JSONL files via {@link
 * de.vvwt.tm.tournament.internal.DefaultAuditLogRepository} (FileChannel + Jackson, per-tournament
 * file isolation). The {@code @Table("audit_log")} annotation and Spring Data JDBC binding are
 * removed — file IO is the persistence backend.
 *
 * <p>Every {@code SetResult} INSERT or UPDATE appends one {@code AuditLogEntry} recording who
 * changed what, when, and why. This satisfies correction traceability per DEC-14 §requirement (a).
 *
 * <h2>Append-only convention</h2>
 *
 * <p>The audit log is append-only by convention. {@link AuditLogRepository} does not expose any
 * delete operation.
 *
 * <h2>tournamentId — non-null invariant</h2>
 *
 * <p>{@code tournamentId} must be non-null. The setter enforces a fast-fail {@link
 * NullPointerException} on null input. All 3 production call-sites supply {@code
 * input.tournamentId()} which is always non-null per O-2 (scoring + match-correction services
 * always have tournament context).
 *
 * <h2>NULL semantics for old values</h2>
 *
 * <p>When a {@code SetResult} is first INSERTed, there is no prior state. In this case {@code
 * team1PointsOld}, {@code team2PointsOld}, and {@code setStateOld} are {@code null}. When a {@code
 * SetResult} is UPDATEd (correction), all three old-value fields are non-null.
 *
 * @see AuditLogRepository
 * @see SetState
 * @see <a href="DEC-14">DEC-14 — V1 persistence model; audit_log file-based carve-out (2026-05-14
 *     amendment)</a>
 * @see <a href="DEC-21">DEC-21 — internal package discipline</a>
 * @see <a href="DEC-22">DEC-22 — TDD Iron Law</a>
 * @see <a href="DEC-35">DEC-35 — entities at public surface (E31S01 promotion)</a>
 * @see <a href="E55S13">E55S13 — file-based audit log isolation</a>
 */
public class AuditLogEntry {

    /** The tournament this audit entry belongs to. NOT NULL (see class Javadoc). */
    private UUID tournamentId;

    /** Surrogate primary key — UUID generated by the application layer before insert. */
    private UUID id;

    /** The match this set result correction belongs to. NOT NULL. */
    private UUID matchId;

    /** The set index within the match (0-based, matching {@code set_result.set_index}). */
    private int setIndex;

    /** Team 1 score before the change. {@code null} on the first INSERT (no prior state). */
    private Integer team1PointsOld;

    /** Team 2 score before the change. {@code null} on the first INSERT (no prior state). */
    private Integer team2PointsOld;

    /** Team 1 score after the change. NOT NULL. */
    private int team1PointsNew;

    /** Team 2 score after the change. NOT NULL. */
    private int team2PointsNew;

    /** {@link SetState} legacy code before the change. {@code null} on first INSERT. */
    private Integer setStateOld;

    /** {@link SetState} legacy code after the change. NOT NULL. */
    private int setStateNew;

    /**
     * Identity of the actor who made the change. {@code null} in default-tenant LAN mode where no
     * login is required.
     */
    private String actorId;

    /** Optional human-readable reason for the correction. {@code null} if no reason was given. */
    private String reason;

    /** Timestamp when the change was recorded. Set by the caller (previously set by DB default). */
    private LocalDateTime changedAt;

    /**
     * Source type of this audit entry (E06S06). Values: {@code "TABLET"} (scoring tablet), {@code
     * "ADMIN"} (admin UI correction), or {@code null} for legacy rows.
     */
    private String sourceType;

    /**
     * Device UUID string when {@code sourceType} is {@code "TABLET"} (E06S06). {@code null} for
     * admin corrections and legacy rows.
     */
    private String sourceDeviceId;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /** Default constructor required by Jackson deserialization and legacy wiring. */
    public AuditLogEntry() {}

    /**
     * Full constructor for programmatic creation by the cascade service.
     *
     * <p>Parameter order: {@code tournamentId} first (DDD aggregate-id-first ordering per
     * AC-IMPL-AUDITLOGENTRY-TOURNAMENTID-FIELD).
     *
     * @param tournamentId the tournament UUID (NOT NULL — fail-fast NPE if null)
     * @param id surrogate primary key (generated by caller via {@code UUID.randomUUID()})
     * @param matchId match FK (NOT NULL)
     * @param setIndex set index within the match
     * @param team1PointsOld old team 1 score ({@code null} on first insert)
     * @param team2PointsOld old team 2 score ({@code null} on first insert)
     * @param team1PointsNew new team 1 score (NOT NULL)
     * @param team2PointsNew new team 2 score (NOT NULL)
     * @param setStateOld old set state legacy code ({@code null} on first insert)
     * @param setStateNew new set state legacy code (NOT NULL)
     * @param actorId identity of the actor ({@code null} in LAN mode)
     * @param reason optional organiser-provided reason ({@code null} if absent)
     * @param changedAt change timestamp
     * @param sourceType audit source type ({@code "TABLET"}, {@code "ADMIN"}, or {@code null})
     * @param sourceDeviceId device UUID string when sourceType is TABLET; {@code null} otherwise
     */
    public AuditLogEntry(
            UUID tournamentId,
            UUID id,
            UUID matchId,
            int setIndex,
            Integer team1PointsOld,
            Integer team2PointsOld,
            int team1PointsNew,
            int team2PointsNew,
            Integer setStateOld,
            int setStateNew,
            String actorId,
            String reason,
            LocalDateTime changedAt,
            String sourceType,
            String sourceDeviceId) {
        this.tournamentId = Objects.requireNonNull(tournamentId, "tournamentId");
        this.id = id;
        this.matchId = matchId;
        this.setIndex = setIndex;
        this.team1PointsOld = team1PointsOld;
        this.team2PointsOld = team2PointsOld;
        this.team1PointsNew = team1PointsNew;
        this.team2PointsNew = team2PointsNew;
        this.setStateOld = setStateOld;
        this.setStateNew = setStateNew;
        this.actorId = actorId;
        this.reason = reason;
        this.changedAt = changedAt;
        this.sourceType = sourceType;
        this.sourceDeviceId = sourceDeviceId;
    }

    // -----------------------------------------------------------------------
    // Type-safe SetState convenience methods
    // -----------------------------------------------------------------------

    /**
     * Returns the old set state as a {@link SetState} enum, or {@code null} if no prior state
     * exists (first INSERT).
     *
     * @return the old state, or {@code null}
     */
    public SetState getSetStateOldAsEnum() {
        return setStateOld == null ? null : SetState.fromLegacyCode(setStateOld);
    }

    /**
     * Returns the new set state as a {@link SetState} enum.
     *
     * @return the new state (never {@code null})
     */
    public SetState getSetStateNewAsEnum() {
        return SetState.fromLegacyCode(setStateNew);
    }

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    public UUID getTournamentId() {
        return tournamentId;
    }

    /**
     * Sets the tournament ID. Throws {@link NullPointerException} on null input (fail-fast per
     * AC-ERROR-HANDLING-NULL-TOURNAMENTID-FAILS-FAST).
     */
    public void setTournamentId(UUID tournamentId) {
        this.tournamentId = Objects.requireNonNull(tournamentId, "tournamentId");
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getMatchId() {
        return matchId;
    }

    public void setMatchId(UUID matchId) {
        this.matchId = matchId;
    }

    public int getSetIndex() {
        return setIndex;
    }

    public void setSetIndex(int setIndex) {
        this.setIndex = setIndex;
    }

    public Integer getTeam1PointsOld() {
        return team1PointsOld;
    }

    public void setTeam1PointsOld(Integer team1PointsOld) {
        this.team1PointsOld = team1PointsOld;
    }

    public Integer getTeam2PointsOld() {
        return team2PointsOld;
    }

    public void setTeam2PointsOld(Integer team2PointsOld) {
        this.team2PointsOld = team2PointsOld;
    }

    public int getTeam1PointsNew() {
        return team1PointsNew;
    }

    public void setTeam1PointsNew(int team1PointsNew) {
        this.team1PointsNew = team1PointsNew;
    }

    public int getTeam2PointsNew() {
        return team2PointsNew;
    }

    public void setTeam2PointsNew(int team2PointsNew) {
        this.team2PointsNew = team2PointsNew;
    }

    public Integer getSetStateOld() {
        return setStateOld;
    }

    public void setSetStateOld(Integer setStateOld) {
        this.setStateOld = setStateOld;
    }

    public int getSetStateNew() {
        return setStateNew;
    }

    public void setSetStateNew(int setStateNew) {
        this.setStateNew = setStateNew;
    }

    public String getActorId() {
        return actorId;
    }

    public void setActorId(String actorId) {
        this.actorId = actorId;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public LocalDateTime getChangedAt() {
        return changedAt;
    }

    public void setChangedAt(LocalDateTime changedAt) {
        this.changedAt = changedAt;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getSourceDeviceId() {
        return sourceDeviceId;
    }

    public void setSourceDeviceId(String sourceDeviceId) {
        this.sourceDeviceId = sourceDeviceId;
    }

    @Override
    public String toString() {
        return "AuditLogEntry{tournamentId="
                + tournamentId
                + ", id="
                + id
                + ", matchId="
                + matchId
                + ", setIndex="
                + setIndex
                + ", setStateOld="
                + setStateOld
                + ", setStateNew="
                + setStateNew
                + ", sourceType="
                + sourceType
                + ", changedAt="
                + changedAt
                + '}';
    }
}
