package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Root entity of the {@code Device} aggregate (DEC-21 public API surface).
 *
 * <p>Plain Java entity for the {@code devices} table. Lives at the Modulith target package {@code
 * de.vvwt.tm.tournament} per DEC-21 §Module layout (boundary-API surface).
 *
 * <p>Uses plain JdbcTemplate persistence via {@link
 * de.vvwt.tm.tournament.internal.DeviceRepository} to avoid Spring Data JDBC entity-mapping
 * conflicts with the parallel legacy {@code de.vvwt.tm.domain.Device} entity that maps to the same
 * {@code devices} table during the reconstruction-in-place phase (DEC-21/DEC-22).
 *
 * <p>Device type constants and status constants mirror the legacy {@code de.vvwt.tm.domain.Device}
 * semantics without importing it.
 *
 * <p>DEC-24: {@code locationId} is nullable — location assignment is a post-registration admin step
 * (performed by {@link DeviceAdminController}, not at registration time).
 *
 * <p>Legacy {@code de.vvwt.tm.domain.Device} and all consumer-context code remain untouched until
 * E21S13 atomic cutover.
 *
 * @see de.vvwt.tm.tournament.internal.DeviceRepository
 * @see de.vvwt.tm.tournament.internal.DefaultDeviceService
 * @see <a href="DEC-21">DEC-21 — Spring Modulith, root package = public API surface</a>
 * @see <a href="DEC-22">DEC-22 — TDD reconstruction-in-place</a>
 * @see <a href="DEC-24">DEC-24 — device location nullable</a>
 * @see <a href="E21S06">E21S06 — Device aggregate reconstruction (inventory line 420)</a>
 */
public class Device {

    // -------------------------------------------------------------------------
    // Status constants
    // -------------------------------------------------------------------------

    /** Device has been registered but not yet assigned to a field/location. */
    public static final String STATUS_REGISTERED = "REGISTERED";

    /** Device has been assigned to a specific field at a location. */
    public static final String STATUS_ASSIGNED = "ASSIGNED";

    /** Device has disconnected (WebSocket connection closed). */
    public static final String STATUS_DISCONNECTED = "DISCONNECTED";

    // -------------------------------------------------------------------------
    // Device type constants
    // -------------------------------------------------------------------------

    /** Scoring tablet: used by referees to enter match results. Requires a PIN for auth. */
    public static final String TYPE_SCORING_TABLET = "SCORING_TABLET";

    /** Display device: passive display showing match state / results. No PIN required. */
    public static final String TYPE_DISPLAY = "DISPLAY";

    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------

    /** Primary key — UUID generated by the application layer before insert. */
    private UUID id;

    /**
     * Tenant scope — NOT NULL. Every device belongs to exactly one tenant. Foreign key references
     * {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Location the device is assigned to — NULLABLE per DEC-24. Set to {@code null} at
     * registration; populated by an admin via {@link DeviceAdminController} after registration.
     * Foreign key references {@code location(id)}.
     */
    private UUID locationId;

    /** Device type — one of {@link #TYPE_SCORING_TABLET}, {@link #TYPE_DISPLAY}. NOT NULL. */
    private String deviceType;

    /** Unique token used by the device to authenticate WebSocket / REST calls. NOT NULL. */
    private String deviceToken;

    /**
     * 4–6 digit PIN used by referees on a SCORING_TABLET to confirm their identity. {@code null}
     * for DISPLAY devices (no PIN required).
     */
    private String pin;

    /**
     * The table/field number this device is assigned to (1-based). {@code null} when the device has
     * no field assignment.
     */
    private Integer assignedField;

    /**
     * Current status of the device — one of {@link #STATUS_REGISTERED}, {@link #STATUS_ASSIGNED},
     * {@link #STATUS_DISCONNECTED}. NOT NULL.
     */
    private String status;

    /** Timestamp of first registration. Set once at registration. */
    private LocalDateTime registeredAt;

    /** Timestamp of the last observed WebSocket activity. Updated by the WebSocket handler. */
    private LocalDateTime lastSeenAt;

    /**
     * Human-readable label for DISPLAY devices (e.g. "Hall B Display"). Configured via {@link
     * DeviceAdminController} after registration. {@code null} for SCORING_TABLET devices unless
     * explicitly set.
     */
    private String deviceName;

    /**
     * JSON configuration blob for DISPLAY devices (e.g. display schema, layout). {@code null} until
     * configured via {@link DeviceAdminController}.
     */
    private String configuration;

    // -------------------------------------------------------------------------
    // Default constructor
    // -------------------------------------------------------------------------

    /** Default constructor. */
    public Device() {}

    /**
     * Full constructor for programmatic creation. Parameter order matches the legacy {@code
     * de.vvwt.tm.domain.Device} constructor for backward compatibility with existing test code.
     *
     * <p>Added in E21S13 cutover — DEC-22 refactor phase fix.
     *
     * @param id primary key
     * @param tenantId tenant scope
     * @param locationId location scope (nullable)
     * @param deviceToken opaque auth token
     * @param pin short numeric PIN (nullable for display devices)
     * @param deviceType device type enum name
     * @param assignedField assigned court field number (nullable)
     * @param status lifecycle status
     * @param registeredAt registration timestamp (nullable)
     * @param lastSeenAt last-seen timestamp (nullable)
     * @param deviceName human-readable device name (nullable)
     * @param configuration JSON configuration string (nullable)
     */
    public Device(
            UUID id,
            UUID tenantId,
            UUID locationId,
            String deviceToken,
            String pin,
            String deviceType,
            Integer assignedField,
            String status,
            LocalDateTime registeredAt,
            LocalDateTime lastSeenAt,
            String deviceName,
            String configuration) {
        this.id = id;
        this.tenantId = tenantId;
        this.locationId = locationId;
        this.deviceToken = deviceToken;
        this.pin = pin;
        this.deviceType = deviceType;
        this.assignedField = assignedField;
        this.status = status;
        this.registeredAt = registeredAt;
        this.lastSeenAt = lastSeenAt;
        this.deviceName = deviceName;
        this.configuration = configuration;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    public UUID getLocationId() {
        return locationId;
    }

    public void setLocationId(UUID locationId) {
        this.locationId = locationId;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getDeviceToken() {
        return deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    public String getPin() {
        return pin;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public Integer getAssignedField() {
        return assignedField;
    }

    public void setAssignedField(Integer assignedField) {
        this.assignedField = assignedField;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getRegisteredAt() {
        return registeredAt;
    }

    public void setRegisteredAt(LocalDateTime registeredAt) {
        this.registeredAt = registeredAt;
    }

    public LocalDateTime getLastSeenAt() {
        return lastSeenAt;
    }

    public void setLastSeenAt(LocalDateTime lastSeenAt) {
        this.lastSeenAt = lastSeenAt;
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    public String getConfiguration() {
        return configuration;
    }

    public void setConfiguration(String configuration) {
        this.configuration = configuration;
    }
}
