package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Spring Data JDBC entity for the {@code match} table (DEC-21, DEC-22, E21S05).
 *
 * <p>Reconstruction-in-place counterpart of {@code de.vvwt.tm.domain.Match} (READ ONLY reference;
 * not imported). Boundary-API of the {@code tournament} Modulith context per inventory line 173 (16
 * importers across {@code slotopt}, {@code display}, {@code print}, {@code timer}, and {@code
 * scoring} contexts — highest import count of any single tournament entity).
 *
 * <h2>Tenant scope (DEC-5, DEC-17)</h2>
 *
 * <p>{@code tenantId} is NOT NULL — every match belongs to exactly one tenant.
 *
 * <h2>TeamAvatar references (DEC-9)</h2>
 *
 * <p>{@code memberAvatar1Id} and {@code memberAvatar2Id} reference {@link TeamAvatar} rows (the
 * team's appearance in a specific phase/group) — not {@link Team} rows directly.
 *
 * <h2>Match state</h2>
 *
 * <p>The {@code state} column stores the legacy integer code from {@link MatchState}. Use {@link
 * #getMatchState()} and {@link #setMatchState(MatchState)} for type-safe access.
 *
 * <h2>Slot coordinates</h2>
 *
 * <p>{@code lapNumber} and {@code fieldNumber} are nullable. A freshly generated match has these
 * {@code null}. E04's slot-optimization client fills them via UPDATE.
 *
 * <h2>@Column annotation requirement</h2>
 *
 * <p>Spring Data JDBC converts {@code memberAvatar1Id} to {@code member_avatar1_id} by default, but
 * the DB column is {@code member_avatar_1_id}. Explicit {@code @Column} is required.
 *
 * @see MatchState
 * @see MatchFormat
 * @see <a href="DEC-21">DEC-21 — Spring Modulith boundary-API placement</a>
 * @see <a href="DEC-22">DEC-22 — TDD Iron Law (reconstruction-in-place)</a>
 * @see <a href="DEC-26">DEC-26 — DAO test governance</a>
 * @see <a href="E21S05">E21S05 — inventory line 173</a>
 */
@Table("match")
public class Match {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /** Tournament this match belongs to. NOT NULL. FK references {@code tournament(id)}. */
    private UUID tournamentId;

    /** Phase this match is part of. NOT NULL. FK references {@code phase(id)}. */
    private UUID phaseId;

    /**
     * First team avatar in the match pairing (DEC-9). NOT NULL. FK references {@code
     * team_avatar(id)}. Explicit {@code @Column} required: Spring Data JDBC would otherwise derive
     * {@code member_avatar1_id} (wrong) instead of {@code member_avatar_1_id}.
     */
    @Column("member_avatar_1_id")
    private UUID memberAvatar1Id;

    /**
     * Second team avatar in the match pairing (DEC-9). NOT NULL. FK references {@code
     * team_avatar(id)}. Explicit {@code @Column} required (see {@code memberAvatar1Id}).
     */
    @Column("member_avatar_2_id")
    private UUID memberAvatar2Id;

    /**
     * Match lifecycle state stored as legacy integer code. Use {@link #getMatchState()} and {@link
     * #setMatchState(MatchState)} for type-safe access.
     */
    private int state;

    /**
     * Maximum number of sets for this match, derived from {@link MatchFormat#getMaxSets()} at match
     * generation time. Defaults to 1 at the schema level; must be set correctly at insert.
     */
    private int setLimit;

    /**
     * Lap (round) number assigned by E04 slot-optimization. {@code null} until slot-optimization
     * runs.
     */
    private Integer lapNumber;

    /**
     * Field number assigned by E04 slot-optimization. {@code null} until slot-optimization runs.
     */
    private Integer fieldNumber;

    /**
     * UUID of the team assigned to referee this match. {@code null} until RefereeAssigner runs. FK
     * references {@code team(id)}.
     */
    private UUID refereeTeamId;

    /**
     * Free-text description or manual override notes for the referee assignment. {@code null} when
     * not set.
     */
    private String refereeDescription;

    /**
     * JSON preference rules for automatic referee assignment. Stored as CLOB. {@code null} when no
     * preferences are configured.
     */
    private String refereePreferenceConfig;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Match() {}

    /**
     * Full constructor for programmatic creation (e.g., by the MatchGenerator).
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tournamentId tournament FK (NOT NULL)
     * @param phaseId phase FK (NOT NULL)
     * @param memberAvatar1Id first team avatar FK (NOT NULL)
     * @param memberAvatar2Id second team avatar FK (NOT NULL)
     * @param state legacy int state code (use {@link MatchState#getLegacyCode()})
     * @param setLimit max sets derived from MatchFormat.maxSets
     * @param lapNumber slot lap — {@code null} until slot-optimization
     * @param fieldNumber slot field — {@code null} until slot-optimization
     * @param refereeTeamId referee team — {@code null} until RefereeAssigner runs
     * @param refereeDescription free-text referee notes — may be {@code null}
     * @param refereePreferenceConfig JSON preference rules — may be {@code null}
     * @param createdAt creation timestamp (may be null; DB sets default)
     */
    public Match(
            UUID id,
            UUID tournamentId,
            UUID phaseId,
            UUID memberAvatar1Id,
            UUID memberAvatar2Id,
            int state,
            int setLimit,
            Integer lapNumber,
            Integer fieldNumber,
            UUID refereeTeamId,
            String refereeDescription,
            String refereePreferenceConfig,
            LocalDateTime createdAt) {
        this.id = id;
        this.tournamentId = tournamentId;
        this.phaseId = phaseId;
        this.memberAvatar1Id = memberAvatar1Id;
        this.memberAvatar2Id = memberAvatar2Id;
        this.state = state;
        this.setLimit = setLimit;
        this.lapNumber = lapNumber;
        this.fieldNumber = fieldNumber;
        this.refereeTeamId = refereeTeamId;
        this.refereeDescription = refereeDescription;
        this.refereePreferenceConfig = refereePreferenceConfig;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Type-safe MatchState convenience methods
    // -------------------------------------------------------------------------

    /**
     * Returns the match lifecycle state as the {@link MatchState} enum.
     *
     * @return the current state
     * @throws IllegalArgumentException if the stored integer code is unknown
     */
    public MatchState getMatchState() {
        return MatchState.fromLegacyCode(this.state);
    }

    /**
     * Sets the match lifecycle state from a {@link MatchState} enum value.
     *
     * @param matchState the new state (must not be {@code null})
     * @throws NullPointerException if {@code matchState} is {@code null}
     */
    public void setMatchState(MatchState matchState) {
        if (matchState == null) {
            throw new NullPointerException("matchState must not be null");
        }
        this.state = matchState.getLegacyCode();
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(UUID tournamentId) {
        this.tournamentId = tournamentId;
    }

    public UUID getPhaseId() {
        return phaseId;
    }

    public void setPhaseId(UUID phaseId) {
        this.phaseId = phaseId;
    }

    public UUID getMemberAvatar1Id() {
        return memberAvatar1Id;
    }

    public void setMemberAvatar1Id(UUID memberAvatar1Id) {
        this.memberAvatar1Id = memberAvatar1Id;
    }

    public UUID getMemberAvatar2Id() {
        return memberAvatar2Id;
    }

    public void setMemberAvatar2Id(UUID memberAvatar2Id) {
        this.memberAvatar2Id = memberAvatar2Id;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public int getSetLimit() {
        return setLimit;
    }

    public void setSetLimit(int setLimit) {
        this.setLimit = setLimit;
    }

    public Integer getLapNumber() {
        return lapNumber;
    }

    public void setLapNumber(Integer lapNumber) {
        this.lapNumber = lapNumber;
    }

    public Integer getFieldNumber() {
        return fieldNumber;
    }

    public void setFieldNumber(Integer fieldNumber) {
        this.fieldNumber = fieldNumber;
    }

    public UUID getRefereeTeamId() {
        return refereeTeamId;
    }

    public void setRefereeTeamId(UUID refereeTeamId) {
        this.refereeTeamId = refereeTeamId;
    }

    public String getRefereeDescription() {
        return refereeDescription;
    }

    public void setRefereeDescription(String refereeDescription) {
        this.refereeDescription = refereeDescription;
    }

    public String getRefereePreferenceConfig() {
        return refereePreferenceConfig;
    }

    public void setRefereePreferenceConfig(String refereePreferenceConfig) {
        this.refereePreferenceConfig = refereePreferenceConfig;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
