package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Boundary-API aggregate entity for the {@code phase} table (DEC-21 public API surface).
 *
 * <p>A {@code Phase} represents one stage within a {@link Tournament} (e.g., preliminary round,
 * finals). Reconstructed in-place per DEC-22 at {@code de.vvwt.tm.tournament.Phase} — the new
 * Modulith boundary-API package (inventory line 177, 12 importers). Legacy {@code
 * de.vvwt.tm.domain.Phase} remains untouched until the E21S13 atomic cutover per DEC-32.
 *
 * <h2>Phase lifecycle</h2>
 *
 * <ul>
 *   <li>{@link PhaseStatus#PENDING} — created; not yet started
 *   <li>{@link PhaseStatus#PREPARED} — match-gen completed, ready for team assignment (E51S05)
 *   <li>{@link PhaseStatus#ASSIGNED} — avatar→team mapping confirmed + referee assigned (E51S05)
 *   <li>{@link PhaseStatus#ACTIVE} — currently in progress
 *   <li>{@link PhaseStatus#COMPLETED} — all matches in this phase are finished
 * </ul>
 *
 * <p>The {@code currentLapNumber} advances during cascade recompute per D-21 step 10. It starts at
 * 0 (no lap has completed yet) and increments as rounds are finalized.
 *
 * <p>No {@code @Component} or {@code @Service} annotations — pure Spring Data JDBC entity per
 * AC-PKG-Phase.
 *
 * <p>Note: Spring Data JDBC entity scanning conflict with {@code de.vvwt.tm.domain.Phase} is
 * avoided by NOT registering a {@code CrudRepository<Phase, UUID>} during the reconstruction-in-
 * place phase (per E21S02 §Deviation pattern). {@link PhaseRepository} uses JdbcTemplate + manual
 * RowMapper. {@link PhaseCrudRepository} will be activated at E21S13 cutover when the legacy entity
 * is deleted.
 *
 * @see PhaseRepository
 * @see <a href="DEC-21">DEC-21 — Spring Modulith, root package = public API surface</a>
 * @see <a href="DEC-22">DEC-22 — TDD reconstruction-in-place</a>
 * @see <a href="E21S03">E21S03 — Phase cluster reconstruction (inventory line 177)</a>
 */
@Table("phase")
public class Phase {

    /**
     * Lifecycle status for a phase.
     *
     * <p>Stored as a VARCHAR in the database (the enum name). The persistence layer stores and
     * reads this as a String; the domain layer works with the enum for type safety.
     */
    public enum PhaseStatus {
        /** Phase is created but not yet started; avatars persisted, match-gen not yet complete. */
        PENDING,
        /**
         * Match-Gen completed; matches persisted with {@code lap=null, field=null}. Slot-Opt may
         * run independently (parallel side-computation per DEC-55 D-6). PENDING → PREPARED via
         * {@code PhaseLifecycleService.transition(phaseId, PREPARED, "match-gen-done")} (E51S05).
         */
        PREPARED,
        /**
         * Avatar→Team-Mapping confirmed (drag&amp;drop commit) AND Referee-Assignment completed.
         * Phase is ready for activation. PREPARED → ASSIGNED via {@code transition(phaseId,
         * ASSIGNED, "assign")} (E51S05 / E51S06). ASSIGNED → ACTIVE requires activation-guard
         * {@code !tournament.optimize OR phase.optimized} (DEC-55 D-6, E51S05).
         */
        ASSIGNED,
        /** Phase is currently in progress (at least one match has been played or is scheduled). */
        ACTIVE,
        /** All matches in this phase have been completed and standings are finalized. */
        COMPLETED
    }

    /** Primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /**
     * Parent tournament — NOT NULL. Foreign key references {@code tournament(id)}. A phase always
     * belongs to exactly one tournament.
     */
    private UUID tournamentId;

    /**
     * Ordering number within the parent tournament. Together with {@code tournamentId}, forms a
     * unique pair (schema UNIQUE constraint). Starts at 1 for the first phase.
     */
    private int sequenceNumber;

    /** Human-readable phase label (e.g., "Vorrunde", "Finale"). */
    private String description;

    /**
     * Current lifecycle status of this phase. Stored as the enum name (VARCHAR) in the database.
     * Application code uses {@link PhaseStatus} for type-safe comparisons.
     */
    private String status;

    /**
     * Active lap index within this phase. Starts at 0 (no lap completed). Incremented automatically
     * during cascade recompute at round finalization.
     */
    private int currentLapNumber;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    /**
     * Slot-optimization completion flag (DEC-55 D-6, E51S01 schema). {@code false} initially.
     * Flipped to {@code true} by {@code SlotOptJobCompletedEvent} listener (E51S04) or by
     * operator-cancel Best-So-Far path (DEC-49 D-11a). Activation-guard: {@code ASSIGNED → ACTIVE}
     * requires {@code !tournament.optimize OR phase.optimized} (E51S05).
     */
    private boolean optimized;

    /**
     * Background-job state audit + restart-recovery column (DEC-55 D-2 + D-8, E51S01 schema).
     * Nullable: {@code null} means no background job has run for this phase yet. Permitted values
     * (enforced at the application layer): {@code "match_gen_running"}, {@code "slot_opt_running"},
     * {@code "idle"}, {@code "cancelled"}, {@code "failed"}. Written by {@code MatchGenJobListener}
     * (E51S03) and {@code SlotOptInvocationListener} (E51S04). Read by {@code
     * JobQueueRecoveryService} (E51S07) to reconcile in-flight jobs on JVM restart.
     */
    private String lastJobState;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Phase() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tournamentId parent tournament (NOT NULL)
     * @param sequenceNumber ordering within the tournament (&ge; 1)
     * @param description human-readable label (NOT NULL)
     * @param status lifecycle status name (e.g., {@code "PENDING"})
     * @param currentLapNumber active lap index (&ge; 0)
     * @param createdAt creation timestamp (may be null; DB sets default)
     */
    public Phase(
            UUID id,
            UUID tournamentId,
            int sequenceNumber,
            String description,
            String status,
            int currentLapNumber,
            LocalDateTime createdAt) {
        this.id = id;
        this.tournamentId = tournamentId;
        this.sequenceNumber = sequenceNumber;
        this.description = description;
        this.status = status;
        this.currentLapNumber = currentLapNumber;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(UUID tournamentId) {
        this.tournamentId = tournamentId;
    }

    public int getSequenceNumber() {
        return sequenceNumber;
    }

    public void setSequenceNumber(int sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getCurrentLapNumber() {
        return currentLapNumber;
    }

    public void setCurrentLapNumber(int currentLapNumber) {
        this.currentLapNumber = currentLapNumber;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns whether slot-optimization has completed for this phase (DEC-55 D-6, E51S03).
     *
     * @return {@code true} if slot-opt has completed; {@code false} otherwise
     */
    public boolean isOptimized() {
        return optimized;
    }

    /**
     * Sets the slot-optimization completion flag (DEC-55 D-6).
     *
     * @param optimized {@code true} when slot-opt completes or is cancelled with Best-So-Far
     */
    public void setOptimized(boolean optimized) {
        this.optimized = optimized;
    }

    /**
     * Returns the current background-job state for this phase (DEC-55 D-2, E51S03).
     *
     * <p>Nullable — {@code null} means no background job has run yet. Non-null values: {@code
     * "match_gen_running"}, {@code "slot_opt_running"}, {@code "idle"}, {@code "cancelled"}, {@code
     * "failed"}.
     *
     * @return the job state string or {@code null}
     */
    public String getLastJobState() {
        return lastJobState;
    }

    /**
     * Sets the background-job state for this phase (DEC-55 D-2).
     *
     * @param lastJobState the job state string; {@code null} resets to "no job run yet"
     */
    public void setLastJobState(String lastJobState) {
        this.lastJobState = lastJobState;
    }
}
