package de.vvwt.tm.tournament;

import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Boundary-API aggregate entity for the {@code phase_breaks} table (DEC-21 public API surface).
 *
 * <p>A {@code PhaseBreak} represents a pause that occurs within a phase at a specific lap boundary.
 * For example, {@code afterLapNumber=4, durationMinutes=40} means a 40-minute break between round 4
 * and round 5 of the phase. Reconstructed in-place per DEC-22 at {@code
 * de.vvwt.tm.tournament.PhaseBreak} — boundary-API candidate per inventory line 178 (consumed by
 * {@code timer/TimerDataService}). Legacy {@code de.vvwt.tm.domain.PhaseBreak} remains untouched
 * until the E21S13 atomic cutover per DEC-32.
 *
 * <p>The schema-level UNIQUE constraint on {@code (phase_id, after_lap_number)} ensures at most one
 * break per lap boundary per phase. The application-layer {@link PhaseBreakService} checks this
 * before persisting.
 *
 * <p>No {@code @Component} or {@code @Service} annotations — pure Spring Data JDBC entity per
 * AC-PKG-PhaseBreak.
 *
 * @see PhaseBreakService
 * @see PhaseBreakRepository
 * @see <a href="DEC-21">DEC-21 — Spring Modulith, root package = public API surface</a>
 * @see <a href="DEC-22">DEC-22 — TDD reconstruction-in-place</a>
 * @see <a href="E21S03">E21S03 — Phase cluster reconstruction (inventory line 178)</a>
 */
@Table("phase_breaks")
public class PhaseBreak {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every phase break belongs to exactly one tenant. Foreign
     * key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Parent phase — NOT NULL. Foreign key references {@code phase(id)}. A phase break always
     * belongs to exactly one phase.
     */
    private UUID phaseId;

    /**
     * The lap number after which this break occurs.
     *
     * <p>A value of {@code 4} means the break occurs in the timeline after lap 4 ends and before
     * lap 5 begins. Must be &ge; 1 and &lt; totalLaps in the phase (validated by {@link
     * PhaseBreakService}).
     */
    private int afterLapNumber;

    /**
     * Duration of the break in minutes. Must be &gt; 0 (enforced by schema CHECK constraint and
     * validated by {@link PhaseBreakService}).
     */
    private int durationMinutes;

    /**
     * Optional organizer-entered display label for the break (e.g., "Mittagspause"). If null, the
     * Laufzettel renders a generic "Pause" label.
     */
    private String label;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public PhaseBreak() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId tenant scope (NOT NULL — DEC-17)
     * @param phaseId parent phase (NOT NULL)
     * @param afterLapNumber lap number after which the break occurs (&ge; 1, &lt; totalLaps)
     * @param durationMinutes break duration in minutes (&gt; 0)
     * @param label optional display label for the break (may be null)
     */
    public PhaseBreak(
            UUID id,
            UUID tenantId,
            UUID phaseId,
            int afterLapNumber,
            int durationMinutes,
            String label) {
        this.id = id;
        this.tenantId = tenantId;
        this.phaseId = phaseId;
        this.afterLapNumber = afterLapNumber;
        this.durationMinutes = durationMinutes;
        this.label = label;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    public UUID getPhaseId() {
        return phaseId;
    }

    public void setPhaseId(UUID phaseId) {
        this.phaseId = phaseId;
    }

    public int getAfterLapNumber() {
        return afterLapNumber;
    }

    public void setAfterLapNumber(int afterLapNumber) {
        this.afterLapNumber = afterLapNumber;
    }

    public int getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }
}
