package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Boundary-API aggregate entity for the {@code round_snapshots} table (DEC-21 public API surface).
 *
 * <p>A {@code RoundSnapshot} captures the complete standings of a phase at a lap-advance boundary.
 * It is written by the round-end snapshot service after each lap completes and is consumed by print
 * output (E08) and the overview UI (E07/display context). Reconstructed in-place per DEC-22 at
 * {@code de.vvwt.tm.tournament.RoundSnapshot} — boundary-API per inventory line 181 (elevated to
 * match public-API status for display/print contexts). Legacy {@code
 * de.vvwt.tm.domain.RoundSnapshot} remains untouched until the E21S13 atomic cutover per DEC-32.
 *
 * <h2>Snapshot uniqueness invariant</h2>
 *
 * <p>The schema enforces {@code UNIQUE (tournament_id, phase_id, lap_number)}: exactly one snapshot
 * exists per (tournament, phase, lap) combination.
 *
 * <p>No {@code @Component} or {@code @Service} annotations — pure Spring Data JDBC entity per
 * AC-PKG-RoundSnapshot.
 *
 * @see RoundSnapshotRepository
 * @see <a href="DEC-21">DEC-21 — Spring Modulith, root package = public API surface</a>
 * @see <a href="DEC-22">DEC-22 — TDD reconstruction-in-place</a>
 * @see <a href="E21S03">E21S03 — Phase cluster reconstruction (inventory line 181)</a>
 */
@Table("round_snapshots")
public class RoundSnapshot {

    /** Surrogate primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every snapshot belongs to exactly one tenant. FK
     * references {@code tenants(id)}.
     */
    private UUID tenantId;

    /** Tournament this snapshot belongs to. NOT NULL. FK references {@code tournament(id)}. */
    private UUID tournamentId;

    /**
     * Phase this snapshot covers. NOT NULL. FK references {@code phase(id)}. Together with {@code
     * tournamentId} and {@code lapNumber}, forms the UNIQUE key.
     */
    private UUID phaseId;

    /**
     * The lap (round) number at which this snapshot was taken. Together with {@code tournamentId}
     * and {@code phaseId}, must be unique (schema UNIQUE constraint).
     */
    private int lapNumber;

    /**
     * JSON serialization of the standings at this lap boundary. Stored as CLOB. NOT NULL — a
     * snapshot without payload has no meaning.
     */
    private String snapshotPayload;

    /**
     * Timestamp when this snapshot was created. Set by the database via DEFAULT CURRENT_TIMESTAMP.
     */
    private LocalDateTime createdAt;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public RoundSnapshot() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id surrogate primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId tenant scope (NOT NULL)
     * @param tournamentId tournament FK (NOT NULL)
     * @param phaseId phase FK (NOT NULL)
     * @param lapNumber lap/round number at snapshot time (&ge; 0)
     * @param snapshotPayload JSON standings payload (NOT NULL)
     * @param createdAt creation timestamp (may be null; DB sets default)
     */
    public RoundSnapshot(
            UUID id,
            UUID tenantId,
            UUID tournamentId,
            UUID phaseId,
            int lapNumber,
            String snapshotPayload,
            LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.tournamentId = tournamentId;
        this.phaseId = phaseId;
        this.lapNumber = lapNumber;
        this.snapshotPayload = snapshotPayload;
        this.createdAt = createdAt;
    }

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    public UUID getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(UUID tournamentId) {
        this.tournamentId = tournamentId;
    }

    public UUID getPhaseId() {
        return phaseId;
    }

    public void setPhaseId(UUID phaseId) {
        this.phaseId = phaseId;
    }

    public int getLapNumber() {
        return lapNumber;
    }

    public void setLapNumber(int lapNumber) {
        this.lapNumber = lapNumber;
    }

    public String getSnapshotPayload() {
        return snapshotPayload;
    }

    public void setSnapshotPayload(String snapshotPayload) {
        this.snapshotPayload = snapshotPayload;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "RoundSnapshot{id="
                + id
                + ", tournamentId="
                + tournamentId
                + ", phaseId="
                + phaseId
                + ", lapNumber="
                + lapNumber
                + ", createdAt="
                + createdAt
                + '}';
    }
}
