// SPDX-FileCopyrightText: Copyright (C) 2026 Thomas Steinke
// SPDX-License-Identifier: AGPL-3.0-or-later
package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Root entity of the {@code Team} aggregate (DEC-21 public API surface).
 *
 * <p>Spring Data JDBC entity for the {@code team} table (inventory line 185, 10 importers via
 * {@code print/LaufzettelAssembler}). Lives at the Modulith target package {@code
 * de.vvwt.tm.tournament} per DEC-21 §Module layout (boundary-API surface).
 *
 * <p>A Team is tournament-scoped (D-20): every team belongs to exactly one tournament. The {@code
 * teamNumber} is a human-readable label (1, 2, 3, …) unique within a tournament. The {@code
 * participate}, {@code refereeAssignment}, and {@code withoutAssessment} flags mirror the legacy
 * {@code de.vvwt.tm.domain.Team} semantics without importing it.
 *
 * <p>Legacy {@code de.vvwt.tm.domain.Team} and all consumer-context code remain untouched until
 * E21S13 atomic cutover per DEC-32.
 *
 * <p>No {@code @Component} or {@code @Service} annotations — pure Spring Data JDBC entity.
 *
 * @see TeamRepository
 * @see <a href="DEC-21">DEC-21 — Spring Modulith, root package = public API surface</a>
 * @see <a href="DEC-22">DEC-22 — TDD reconstruction-in-place</a>
 * @see <a href="DEC-9">DEC-9 — TeamAvatar structural identity</a>
 * @see <a href="E21S04">E21S04 — Team aggregate reconstruction (inventory line 185)</a>
 */
public class Team {

    /** Primary key — UUID generated by the application layer before insert. */
    private UUID id;

    /**
     * Parent tournament — NOT NULL per D-20. Teams are tournament-scoped. Foreign key references
     * {@code tournament(id)}.
     */
    private UUID tournamentId;

    /**
     * Human-readable team identifier within this tournament (legacy parity). Together with {@code
     * tournamentId}, forms a unique pair (schema UNIQUE constraint).
     */
    private int teamNumber;

    /** Human-readable team name or label (NOT NULL in schema). */
    private String description;

    /**
     * Whether this team is actively participating in the tournament. Defaults to {@code true}. A
     * non-participating team may be registered but excluded from match generation.
     */
    private boolean participate;

    /**
     * Whether this team provides a referee for matches where it is not playing (D-28). Defaults to
     * {@code false}.
     */
    private boolean refereeAssignment;

    /**
     * If {@code true}, this team is excluded from normal standing calculations and always appears
     * last in rankings (D-26, legacy parity). Defaults to {@code false}.
     */
    private boolean withoutAssessment;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Team() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tournamentId parent tournament (NOT NULL per D-20)
     * @param teamNumber human-readable team number (unique within tournament)
     * @param description team name/label (NOT NULL)
     * @param participate whether the team participates (default: true)
     * @param refereeAssignment whether the team provides a referee (default: false)
     * @param withoutAssessment whether the team is excluded from standings (default: false)
     * @param createdAt creation timestamp (may be null; DB sets default)
     */
    public Team(
            UUID id,
            UUID tournamentId,
            int teamNumber,
            String description,
            boolean participate,
            boolean refereeAssignment,
            boolean withoutAssessment,
            LocalDateTime createdAt) {
        this.id = id;
        this.tournamentId = tournamentId;
        this.teamNumber = teamNumber;
        this.description = description;
        this.participate = participate;
        this.refereeAssignment = refereeAssignment;
        this.withoutAssessment = withoutAssessment;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(UUID tournamentId) {
        this.tournamentId = tournamentId;
    }

    public int getTeamNumber() {
        return teamNumber;
    }

    public void setTeamNumber(int teamNumber) {
        this.teamNumber = teamNumber;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isParticipate() {
        return participate;
    }

    public void setParticipate(boolean participate) {
        this.participate = participate;
    }

    public boolean isRefereeAssignment() {
        return refereeAssignment;
    }

    public void setRefereeAssignment(boolean refereeAssignment) {
        this.refereeAssignment = refereeAssignment;
    }

    public boolean isWithoutAssessment() {
        return withoutAssessment;
    }

    public void setWithoutAssessment(boolean withoutAssessment) {
        this.withoutAssessment = withoutAssessment;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
