package de.vvwt.tm.tournament;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Root aggregate of the {@code tournament} bounded context (DEC-21 public API surface).
 *
 * <p>Spring Data JDBC entity for the {@code tournament} table. Maps the same columns as the legacy
 * {@code de.vvwt.tm.domain.Tournament} (inventory line 190) but lives at the Modulith target
 * package {@code de.vvwt.tm.tournament} per DEC-21 §Module layout.
 *
 * <p>The {@code tournament} table is the hub aggregate of the TM domain. Every downstream Track-3
 * context ({@code scoring}, {@code certificate}, {@code print}, {@code display}, {@code timer},
 * {@code slotopt-integration}) depends on this aggregate as its root reference.
 *
 * <h2>Status lifecycle</h2>
 *
 * <ul>
 *   <li>{@code DRAFT} — created; teams are being registered
 *   <li>{@code PLANNED} — draft applied; phases created; no phase is active yet
 *   <li>{@code ACTIVE} — at least one phase is in progress
 *   <li>{@code COMPLETED} — all phases have completed
 *   <li>{@code CANCELLED} — organizer cancelled the tournament
 * </ul>
 *
 * <p>DEC-5 single-active invariant: at most one ACTIVE tournament exists per tenant. Enforced at
 * the schema level via the {@code active_sentinel} generated column (V2 migration).
 *
 * <p>No {@code @Component} or {@code @Service} annotations — pure Spring Data JDBC entity per
 * AC-PKG-Tournament.
 *
 * @see <a href="DEC-21">DEC-21 — Spring Modulith, root package = public API surface</a>
 * @see <a href="DEC-22">DEC-22 — TDD reconstruction-in-place</a>
 * @see <a href="E21S02">E21S02 — Tournament aggregate reconstruction (inventory line 190)</a>
 */
@Table("tournament")
public class Tournament {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /** Human-readable tournament label (e.g., "VVW Hallenturnier 2026"). */
    private String description;

    /**
     * Match format for all matches in this tournament. Stored as the enum name (VARCHAR). Valid
     * values: {@code BEST_OF_1}, {@code BEST_OF_3}, {@code BEST_OF_5}, {@code BEST_OF_7}, {@code
     * FIXED_2_SETS}.
     */
    private String matchFormat;

    /** Spring bean id of the {@code ScoringRule} implementation to use. */
    private String scoringRuleId;

    /** Spring bean id of the {@code SetValidationRule} implementation to use. */
    private String setValidationRuleId;

    /** Spring bean id of the {@code MatchGenerator} implementation to use. */
    private String matchGeneratorId;

    /**
     * Tournament lifecycle status. Defaults to {@code DRAFT} at the schema level. Valid values:
     * {@code DRAFT}, {@code PLANNED}, {@code ACTIVE}, {@code COMPLETED}, {@code CANCELLED}.
     */
    private String status;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    /** Optional tournament appointment date/time. May be {@code null}. */
    private LocalDateTime appointment;

    /**
     * Number of courts (fields) available for this tournament. Must be ≥ 1; validated at the
     * service layer.
     */
    @Column("field_count")
    private int fieldCount;

    /**
     * Number of teams participating in this tournament. Must be ≥ 2; validated at the service
     * layer.
     */
    @Column("team_count")
    private int teamCount;

    /**
     * Optional planned start time for the tournament. Time-of-day only — no date component.
     * Nullable: tournaments without print output do not require a start time.
     */
    @Column("planned_start_time")
    private LocalTime plannedStartTime;

    /**
     * Location this tournament is hosted at (DEC-39 D2). NOT NULL. Foreign key references {@code
     * tenant/locations(id)}.
     */
    @Column("location_id")
    private UUID locationId;

    /**
     * Draft configuration stored as a JSON text blob. Nullable: {@code null} means no draft has
     * been configured yet. Cleared when the draft is applied — phases are the source of truth from
     * that point on.
     */
    @Column("draft_json")
    private String draftJson;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Tournament() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param description human-readable label
     * @param matchFormat match format enum name
     * @param scoringRuleId Spring bean id for scoring rule
     * @param setValidationRuleId Spring bean id for set validation rule
     * @param matchGeneratorId Spring bean id for match generator
     * @param status lifecycle status (e.g., {@code "DRAFT"})
     * @param createdAt creation timestamp (may be null; DB sets default)
     * @param appointment optional tournament date
     * @param fieldCount court count (≥ 1)
     * @param teamCount team count (≥ 2)
     * @param plannedStartTime optional time-of-day for print timeline (may be null)
     */
    public Tournament(
            UUID id,
            String description,
            String matchFormat,
            String scoringRuleId,
            String setValidationRuleId,
            String matchGeneratorId,
            String status,
            LocalDateTime createdAt,
            LocalDateTime appointment,
            int fieldCount,
            int teamCount,
            LocalTime plannedStartTime) {
        this.id = id;
        this.description = description;
        this.matchFormat = matchFormat;
        this.scoringRuleId = scoringRuleId;
        this.setValidationRuleId = setValidationRuleId;
        this.matchGeneratorId = matchGeneratorId;
        this.status = status;
        this.createdAt = createdAt;
        this.appointment = appointment;
        this.fieldCount = fieldCount;
        this.teamCount = teamCount;
        this.plannedStartTime = plannedStartTime;
    }

    /**
     * 11-param constructor for backward compatibility with pre-E21S10 test code that did not pass
     * {@code plannedStartTime}.
     *
     * <p>Updated in E45S06 — tenantId removed. Delegates to the full constructor with {@code
     * plannedStartTime = null}.
     */
    public Tournament(
            UUID id,
            String description,
            String matchFormat,
            String scoringRuleId,
            String setValidationRuleId,
            String matchGeneratorId,
            String status,
            LocalDateTime createdAt,
            LocalDateTime appointment,
            int fieldCount,
            int teamCount) {
        this(
                id,
                description,
                matchFormat,
                scoringRuleId,
                setValidationRuleId,
                matchGeneratorId,
                status,
                createdAt,
                appointment,
                fieldCount,
                teamCount,
                null);
    }

    /**
     * 8-param constructor for backward compatibility with pre-E21S05 test code that did not pass
     * {@code appointment}, {@code fieldCount}, {@code teamCount}, or {@code plannedStartTime}.
     *
     * <p>Updated in E45S06 — tenantId removed. Delegates to the full constructor with optional
     * fields as null/zero.
     */
    public Tournament(
            UUID id,
            String description,
            String matchFormat,
            String scoringRuleId,
            String setValidationRuleId,
            String matchGeneratorId,
            String status,
            LocalDateTime createdAt) {
        this(
                id,
                description,
                matchFormat,
                scoringRuleId,
                setValidationRuleId,
                matchGeneratorId,
                status,
                createdAt,
                null,
                1,
                2,
                null);
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMatchFormat() {
        return matchFormat;
    }

    public void setMatchFormat(String matchFormat) {
        this.matchFormat = matchFormat;
    }

    public String getScoringRuleId() {
        return scoringRuleId;
    }

    public void setScoringRuleId(String scoringRuleId) {
        this.scoringRuleId = scoringRuleId;
    }

    public String getSetValidationRuleId() {
        return setValidationRuleId;
    }

    public void setSetValidationRuleId(String setValidationRuleId) {
        this.setValidationRuleId = setValidationRuleId;
    }

    public String getMatchGeneratorId() {
        return matchGeneratorId;
    }

    public void setMatchGeneratorId(String matchGeneratorId) {
        this.matchGeneratorId = matchGeneratorId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getAppointment() {
        return appointment;
    }

    public void setAppointment(LocalDateTime appointment) {
        this.appointment = appointment;
    }

    public int getFieldCount() {
        return fieldCount;
    }

    public void setFieldCount(int fieldCount) {
        this.fieldCount = fieldCount;
    }

    public int getTeamCount() {
        return teamCount;
    }

    public void setTeamCount(int teamCount) {
        this.teamCount = teamCount;
    }

    public LocalTime getPlannedStartTime() {
        return plannedStartTime;
    }

    public void setPlannedStartTime(LocalTime plannedStartTime) {
        this.plannedStartTime = plannedStartTime;
    }

    public UUID getLocationId() {
        return locationId;
    }

    public void setLocationId(UUID locationId) {
        this.locationId = locationId;
    }

    public String getDraftJson() {
        return draftJson;
    }

    public void setDraftJson(String draftJson) {
        this.draftJson = draftJson;
    }
}
