spring:
  application:
    name: vvwt-slotopt-dispatcher
  datasource:
    url: jdbc:h2:mem:dispatcher;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  flyway:
    locations: classpath:db/migration/identity,classpath:db/migration/audit
  sql:
    init:
      platform: h2

server:
  port: 8080
