package de.vvwt.tm.web.certificate;

import static org.assertj.core.api.Assertions.assertThat;

import de.vvwt.tm.web.WebModuleTestConfig;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.mustache.servlet.view.MustacheViewResolver;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.servlet.View;

/**
 * IT verifying that the system-default Mustache certificate templates ({@code
 * certificate/print.mustache} and {@code certificate/print-all.mustache}) render correctly with the
 * two-partial topology introduced in E46S04.
 *
 * <p>DEC-22 Iron Law — RED-first: all four test methods fail against the pre-E46S04 codebase
 * (legacy Arial layout templates, no partials, no embedded Base64 fonts, no {@code tom_label_*}
 * substitution) and pass after the E46S04 production changes land.
 *
 * <h2>Test strategy</h2>
 *
 * <p>The tests directly invoke Spring Mustache view-resolution via the auto-configured {@link
 * MustacheViewResolver} bean. This exercises the actual partial-include resolution path (jmustache
 * + Spring Boot Mustache auto-configuration + {@code classpath:/templates/} prefix) without
 * requiring a full HTTP request — no tournament, no standings, no custom-uploaded template needed.
 * The rendered HTML body is asserted directly.
 *
 * <h2>Test model</h2>
 *
 * <p>The populated {@code singleCertificate} model contains the canonical 13 {@code tom_*}
 * variables per {@code DefaultCertificateTemplateService.VARIABLES} (E46S03 contract):
 *
 * <ul>
 *   <li>Data variables: {@code tom_placement}, {@code tom_team_name}, {@code tom_team_photo},
 *       {@code tom_tournament_name}, {@code tom_date}, {@code tom_location}, {@code tom_organizer}
 *   <li>Label variables: {@code tom_label_certificate}, {@code tom_label_place}, {@code
 *       tom_label_achieved_by}, {@code tom_label_team_photo}, {@code tom_label_generated_by},
 *       {@code tom_label_on}
 * </ul>
 *
 * @see CertificateRenderController
 * @see MustacheViewResolver
 * @see <a href="DEC-22">DEC-22 — TDD Iron Law (RED-first)</a>
 * @see <a href="DEC-15">DEC-15 — Self-host: no external font fetch</a>
 * @see <a href="DEC-16">DEC-16 — Offline rendering</a>
 * @since E46S04
 */
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        classes = de.vvwt.tm.TournamentManagerApplication.class)
@Import({WebModuleTestConfig.class, SystemDefaultCertificateTemplateIT.TestAdminCredentials.class})
@ActiveProfiles("test")
@DisplayName("System-default certificate template IT — E46S04")
class SystemDefaultCertificateTemplateIT {

    @Autowired private MustacheViewResolver mustacheViewResolver;

    // =========================================================================
    // Shared model fixture
    // =========================================================================

    /**
     * Builds the canonical 13-key {@code tom_}-prefixed model fixture (AC-RENDER-* + E46S03
     * contract). Uses ASCII English placeholder values — decoupled from {@code messages.properties}
     * translation choices.
     */
    private Map<String, Object> buildSingleCertificateModel() {
        Map<String, Object> cert = new HashMap<>();
        cert.put("tom_placement", "1");
        cert.put("tom_team_name", "TestTeam");
        cert.put("tom_team_photo", "/api/photo/teams/test-uuid");
        cert.put("tom_tournament_name", "TestTournament");
        cert.put("tom_date", "01. Januar 2026");
        cert.put("tom_location", "TestLocation");
        cert.put("tom_organizer", "TestOrganizer");
        cert.put("tom_label_certificate", "CERTIFICATE");
        cert.put("tom_label_place", "PLACE");
        cert.put("tom_label_achieved_by", "achieved by");
        cert.put("tom_label_team_photo", "Team Photo");
        cert.put("tom_label_generated_by", "generated by");
        cert.put("tom_label_on", "on");
        // Convenience boolean — mirrors DefaultCertificateAssembler.buildMustacheMap()
        cert.put("tom_has_photo", true);
        return cert;
    }

    /**
     * Renders a named Mustache view with the given model and returns the rendered HTML string.
     *
     * @param viewName the Mustache view name (e.g., {@code "certificate/print"})
     * @param model the template model
     * @return rendered HTML body
     * @throws Exception if view resolution or rendering fails
     */
    private String renderView(String viewName, Map<String, Object> model) throws Exception {
        View view = mustacheViewResolver.resolveViewName(viewName, java.util.Locale.GERMAN);
        assertThat(view).as("View '" + viewName + "' must resolve").isNotNull();

        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();
        view.render(model, request, response);
        return response.getContentAsString();
    }

    // =========================================================================
    // AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS
    // =========================================================================

    /**
     * AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: renders {@code certificate/print} and asserts
     * the system-default two-partial topology is active.
     *
     * <p>Assertions:
     *
     * <ul>
     *   <li>contains {@code data:font/woff2;base64,} exactly twice (two {@code @font-face} blocks)
     *   <li>contains {@code font-weight: 700} and {@code font-weight: 800}
     *   <li>does NOT contain unrendered Mustache placeholder ({@code {{} or {@code }}) — all
     *       variables substituted
     *   <li>does NOT contain any of the German placeholder names from AC-NO-GERMAN-PLACEHOLDER-REMAINS
     *   <li>does NOT contain {@code src: url(http} or {@code src: url('http} (no external font URL)
     * </ul>
     */
    @Test
    @DisplayName(
            "AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: print.mustache renders embedded Base64"
                    + " fonts + tom_label_* substitution")
    void rendersEmbeddedFontsAndLabels() throws Exception {
        Map<String, Object> cert = buildSingleCertificateModel();
        Map<String, Object> model = new HashMap<>();
        model.put("singleCertificate", cert);

        String html = renderView("certificate/print", model);

        // Two @font-face with Base64 WOFF2 data-URIs (Bold 700 + ExtraBold 800)
        long fontUriCount = html.lines().filter(l -> l.contains("data:font/woff2;base64,")).count();
        // Count occurrences by simple scan (not line-based — base64 is a single long line)
        int fontUriOccurrences = countOccurrences(html, "data:font/woff2;base64,");
        assertThat(fontUriOccurrences)
                .as(
                        "AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: rendered output must contain"
                                + " 'data:font/woff2;base64,' exactly twice (one per @font-face)")
                .isEqualTo(2);

        assertThat(html)
                .as("AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: must contain font-weight: 700")
                .contains("font-weight: 700");
        assertThat(html)
                .as("AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: must contain font-weight: 800")
                .contains("font-weight: 800");

        // No unrendered Mustache placeholders (all tom_* variables must be substituted)
        assertThat(html)
                .as(
                        "AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: no unrendered Mustache"
                                + " placeholder {{ or }} in rendered HTML")
                .doesNotContain("{{")
                .doesNotContain("}}");

        // No German placeholder names from legacy contract
        assertThat(html)
                .as("AC-NO-GERMAN-PLACEHOLDER-REMAINS: no legacy German placeholder names")
                .doesNotContain("turnier_name")
                .doesNotContain("verein")
                .doesNotContain("foto_base64")
                .doesNotContain("font_700_base64")
                .doesNotContain("font_800_base64");

        // No external font fetch URL inside @font-face src
        assertThat(html)
                .as(
                        "AC-NO-EXTERNAL-FONT-FETCH: no http/https URL in font @font-face src"
                                + " declarations")
                .doesNotContain("src: url(http")
                .doesNotContain("src: url('http")
                .doesNotContain("src: url(\"http");

        // Labels were substituted
        assertThat(html)
                .as(
                        "AC-RENDER-PRODUCES-EMBEDDED-FONTS-AND-LABELS: tom_label_certificate value"
                                + " 'CERTIFICATE' present in rendered output")
                .contains("CERTIFICATE");
    }

    // =========================================================================
    // AC-RENDER-PRINT-ALL-N-PAGES + AC-PAGE-BREAK-CSS-IN-STYLES-PARTIAL
    // =========================================================================

    /**
     * AC-RENDER-PRINT-ALL-N-PAGES: renders {@code certificate/print-all} with N=2 certificate
     * entries and asserts multi-page layout correctness.
     *
     * <p>Also covers AC-PAGE-BREAK-CSS-IN-STYLES-PARTIAL (the rendered {@code <style>} block must
     * contain page-break CSS).
     */
    @Test
    @DisplayName(
            "AC-RENDER-PRINT-ALL-N-PAGES: print-all.mustache renders N=2 certificates — one"
                    + " styles partial, N page tiles, page-break CSS")
    void rendersPrintAllNPages() throws Exception {
        Map<String, Object> cert1 = buildSingleCertificateModel();
        cert1.put("tom_team_name", "TeamAlpha");
        cert1.put("tom_placement", "1");
        cert1.put("showPageBreak", false);

        Map<String, Object> cert2 = new HashMap<>(buildSingleCertificateModel());
        cert2.put("tom_team_name", "TeamBeta");
        cert2.put("tom_placement", "2");
        cert2.put("showPageBreak", true);

        Map<String, Object> model = new HashMap<>();
        model.put("certificates", List.of(cert1, cert2));

        String html = renderView("certificate/print-all", model);

        // One <html> document
        assertThat(countOccurrences(html, "<html"))
                .as("AC-RENDER-PRINT-ALL-N-PAGES: exactly one <html> opening tag")
                .isEqualTo(1);
        assertThat(countOccurrences(html, "</html>"))
                .as("AC-RENDER-PRINT-ALL-N-PAGES: exactly one </html> closing tag")
                .isEqualTo(1);

        // One <head> block (styles partial included once)
        assertThat(countOccurrences(html, "<head>"))
                .as("AC-RENDER-PRINT-ALL-N-PAGES: exactly one <head> block")
                .isEqualTo(1);

        // Exactly 2 font data-URIs total (NOT 4 — styles partial included only once in head)
        int fontUriOccurrences = countOccurrences(html, "data:font/woff2;base64,");
        assertThat(fontUriOccurrences)
                .as(
                        "AC-RENDER-PRINT-ALL-N-PAGES: exactly 2 font data-URIs (styles partial"
                                + " rendered once in head, not once per team)")
                .isEqualTo(2);

        // N=2 certificate page tiles
        int pageDivCount = countOccurrences(html, "<div class=\"page\">");
        assertThat(pageDivCount)
                .as(
                        "AC-RENDER-PRINT-ALL-N-PAGES: exactly 2 <div class=\"page\"> tiles (one"
                                + " per certificate entry)")
                .isEqualTo(2);

        // Both team names present in document order
        int alpha = html.indexOf("TeamAlpha");
        int beta = html.indexOf("TeamBeta");
        assertThat(alpha).as("TeamAlpha must appear in rendered output").isGreaterThan(-1);
        assertThat(beta).as("TeamBeta must appear in rendered output").isGreaterThan(-1);
        assertThat(alpha)
                .as("TeamAlpha (placement 1) must appear before TeamBeta (placement 2)")
                .isLessThan(beta);

        // AC-PAGE-BREAK-CSS-IN-STYLES-PARTIAL: styles partial contains page-break rules
        assertThat(html)
                .as(
                        "AC-PAGE-BREAK-CSS-IN-STYLES-PARTIAL: rendered HTML must contain"
                                + " page-break-after: always or break-after: page in <style> block")
                .satisfiesAnyOf(
                        h -> assertThat(h).contains("page-break-after: always"),
                        h -> assertThat(h).contains("break-after: page"));
    }

    // =========================================================================
    // AC-NO-EXTERNAL-FONT-FETCH
    // =========================================================================

    /**
     * AC-NO-EXTERNAL-FONT-FETCH: both wrappers render with zero {@code @font-face} src containing
     * an {@code http://} or {@code https://} URL.
     */
    @Test
    @DisplayName(
            "AC-NO-EXTERNAL-FONT-FETCH: neither print.mustache nor print-all.mustache renders"
                    + " @font-face with external URL")
    void noExternalFontFetch() throws Exception {
        Map<String, Object> cert = buildSingleCertificateModel();

        Map<String, Object> singleModel = new HashMap<>();
        singleModel.put("singleCertificate", cert);
        String singleHtml = renderView("certificate/print", singleModel);

        Map<String, Object> cert2 = new HashMap<>(buildSingleCertificateModel());
        cert2.put("showPageBreak", false);
        Map<String, Object> allModel = new HashMap<>();
        allModel.put("certificates", List.of(cert2));
        String allHtml = renderView("certificate/print-all", allModel);

        for (String html : new String[] {singleHtml, allHtml}) {
            assertThat(html)
                    .as("AC-NO-EXTERNAL-FONT-FETCH: no external font URL in @font-face src")
                    .doesNotContain("src: url(http")
                    .doesNotContain("src: url('http")
                    .doesNotContain("src: url(\"http");
        }
    }

    // =========================================================================
    // AC-OFL-IN-JAR
    // =========================================================================

    /**
     * AC-OFL-IN-JAR: the OFL license file is present at the canonical classpath path and starts
     * with {@code Copyright}.
     */
    @Test
    @DisplayName(
            "AC-OFL-IN-JAR: PlusJakartaSans-OFL.txt present at META-INF/licenses/ and starts with"
                    + " Copyright")
    void oflResourceInJar() throws Exception {
        try (java.io.InputStream is =
                getClass()
                        .getClassLoader()
                        .getResourceAsStream("META-INF/licenses/PlusJakartaSans-OFL.txt")) {
            assertThat(is)
                    .as(
                            "AC-OFL-IN-JAR: META-INF/licenses/PlusJakartaSans-OFL.txt must be"
                                    + " present on the classpath")
                    .isNotNull();
            byte[] bytes = is.readAllBytes();
            String content = new String(bytes, java.nio.charset.StandardCharsets.UTF_8);
            assertThat(content.stripLeading())
                    .as(
                            "AC-OFL-IN-JAR: OFL.txt must start with 'Copyright' (first non-empty"
                                    + " line per OFL.txt convention)")
                    .startsWith("Copyright");
            assertThat(content)
                    .as("AC-OFL-IN-JAR: must contain SIL OPEN FONT LICENSE Version 1.1 marker")
                    .contains("SIL OPEN FONT LICENSE Version 1.1");
        }
    }

    // =========================================================================
    // Utility
    // =========================================================================

    /** Counts the number of non-overlapping occurrences of {@code needle} in {@code haystack}. */
    private static int countOccurrences(String haystack, String needle) {
        int count = 0;
        int idx = 0;
        while ((idx = haystack.indexOf(needle, idx)) != -1) {
            count++;
            idx += needle.length();
        }
        return count;
    }

    // =========================================================================
    // Test admin credentials stub (required by @SpringBootTest + auth wiring)
    // =========================================================================

    @org.springframework.boot.test.context.TestConfiguration
    static class TestAdminCredentials {
        @org.springframework.context.annotation.Bean("webItAdminCredentialsProvider")
        @org.springframework.context.annotation.Primary
        de.vvwt.tm.auth.AdminCredentialsProvider testAdminCredentialsProvider(
                org.springframework.security.crypto.password.PasswordEncoder encoder) {
            String hash = encoder.encode("E46S04-test-password");
            return () -> hash;
        }
    }
}
