package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code activity_types} table (E08S02, AC2).
 *
 * <p>An {@code ActivityType} represents an organizer-defined non-match activity that is
 * automatically assigned to teams during their free rounds (e.g., "Mannschaftsfoto" —
 * team photo). The assignment algorithm is implemented in the assignment service (E08S04);
 * this entity captures only the configuration.
 *
 * <h2>Assignment rule storage (AC3)</h2>
 * <p>The {@code assignment_rule} field stores the {@linkplain AssignmentRule#name() enum name}
 * as a VARCHAR. This allows new rules to be added post-V1 by adding a new enum constant and
 * implementing the rule in E08S04 — no schema migration required.
 *
 * <h2>Capacity limit (AC6)</h2>
 * <p>{@code capacityPerRound} is nullable. {@code null} means unlimited — no cap on how many
 * teams can be assigned to this activity in a single round. A non-null value must be &gt; 0
 * (enforced by a CHECK constraint in the schema and a validation guard in the service layer).
 *
 * <h2>Tenant scope (AC7, DEC-5, DEC-17)</h2>
 * <p>{@code tenantId} is NOT NULL. All repository operations are tenant-scoped via
 * {@link de.vvwt.tm.domain.repo.TenantScopedRepository}.
 *
 * @see AssignmentRule
 * @see de.vvwt.tm.domain.repo.ActivityTypeRepository
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E08S02.story.md">Story E08S02</a>
 */
@Table("activity_types")
public class ActivityType {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Parent tournament — NOT NULL. Foreign key references {@code tournament(id)}.
     * An activity type always belongs to exactly one tournament.
     */
    private UUID tournamentId;

    /**
     * Human-readable activity name (e.g., "Mannschaftsfoto"). NOT NULL.
     * Unique within a tournament per the {@code uq_activity_types_tournament_name} constraint.
     */
    private String name;

    /**
     * Assignment rule identifier — stored as the {@link AssignmentRule} enum name.
     * NOT NULL. V1 value: {@code "FIRST_FREE_ROUND"}.
     *
     * <p>Domain code that needs type-safe access should use
     * {@code AssignmentRule.valueOf(assignmentRule)}.
     */
    private String assignmentRule;

    /**
     * Optional capacity limit: maximum number of teams that can be assigned this activity
     * in a single round. {@code null} means unlimited. Non-null must be &gt; 0.
     */
    private Integer capacityPerRound;

    /**
     * Display ordering for the Laufzettel when multiple activities occur in the same round.
     * NOT NULL. Lower values appear first.
     */
    private int sortOrder;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every activity type belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public ActivityType() {
    }

    /**
     * Full constructor for programmatic creation.
     *
     * @param id               primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tournamentId     parent tournament (NOT NULL)
     * @param name             activity name, unique within the tournament (NOT NULL)
     * @param assignmentRule   rule identifier — {@link AssignmentRule} name (NOT NULL)
     * @param capacityPerRound max teams per round (nullable; non-null must be &gt; 0)
     * @param sortOrder        display ordering (NOT NULL)
     * @param tenantId         tenant scope (NOT NULL)
     */
    public ActivityType(UUID id, UUID tournamentId, String name,
                        String assignmentRule, Integer capacityPerRound,
                        int sortOrder, UUID tenantId) {
        this.id = id;
        this.tournamentId = tournamentId;
        this.name = name;
        this.assignmentRule = assignmentRule;
        this.capacityPerRound = capacityPerRound;
        this.sortOrder = sortOrder;
        this.tenantId = tenantId;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTournamentId() { return tournamentId; }
    public void setTournamentId(UUID tournamentId) { this.tournamentId = tournamentId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getAssignmentRule() { return assignmentRule; }
    public void setAssignmentRule(String assignmentRule) { this.assignmentRule = assignmentRule; }

    public Integer getCapacityPerRound() { return capacityPerRound; }
    public void setCapacityPerRound(Integer capacityPerRound) { this.capacityPerRound = capacityPerRound; }

    public int getSortOrder() { return sortOrder; }
    public void setSortOrder(int sortOrder) { this.sortOrder = sortOrder; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }
}
