package de.vvwt.tm.domain;

import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Spring Data JDBC entity for the {@code audit_log} table (E03S04, AC4, D-22, D-36).
 *
 * <p>Every {@code SetResult} INSERT (first entry) or UPDATE (correction) appends one {@code
 * AuditLogEntry} row recording who changed what, when, and why. This satisfies the correction
 * traceability requirement of D-22 without event-sourcing infrastructure (per DEC-14).
 *
 * <h2>Append-only convention (AC13)</h2>
 *
 * <p>The {@code audit_log} table is append-only by convention. The repository layer (E03S05)
 * explicitly forbids {@code UPDATE} and {@code DELETE} operations on this table. H2 does not
 * support triggers that could enforce this at the DB level; the application-layer ban is the
 * enforcement mechanism. Direct SQL via a DBA connection can still modify the table — this is
 * considered outside the V1 trust boundary.
 *
 * <h2>NULL semantics for old values</h2>
 *
 * <p>When a {@code SetResult} is first INSERTed, there is no prior state. In this case {@code
 * team1PointsOld}, {@code team2PointsOld}, and {@code setStateOld} are {@code null}. When a {@code
 * SetResult} is UPDATEd (correction), all three old-value fields are non-null.
 *
 * <h2>Actor identity</h2>
 *
 * <p>{@code actorId} may be {@code null} in default-tenant LAN mode where no login is required
 * (DEC-5, DEC-17 default-tenant invariant). It is populated when an authenticated cloud-tenant
 * session is available.
 *
 * <h2>Tenant scope (DEC-5, DEC-17)</h2>
 *
 * <p>{@code tenantId} is NOT NULL — every audit log entry belongs to exactly one tenant.
 *
 * <h2>Source distinction (E06S06, AC8)</h2>
 *
 * <p>{@code sourceType} and {@code sourceDeviceId} distinguish entries from the scoring tablet
 * ({@code "TABLET"}) vs. admin UI corrections ({@code "ADMIN"}). Both are {@code null} on legacy
 * rows written before E06S06.
 *
 * @see SetResult
 * @see SetState
 * @see <a
 *     href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S04.story.md">Story
 *     E03S04</a>
 * @see <a
 *     href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E06S06.story.md">Story
 *     E06S06</a>
 */
@Table("audit_log")
public class AuditLogEntry {

    /** Surrogate primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every audit entry belongs to exactly one tenant. FK
     * references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * The match this set result correction belongs to. NOT NULL. FK references {@code match(id)}.
     */
    private UUID matchId;

    /** The set index within the match (0-based, matching {@code set_result.set_index}). */
    private int setIndex;

    /** Team 1 score before the change. {@code null} on the first INSERT (no prior state). */
    private Integer team1PointsOld;

    /** Team 2 score before the change. {@code null} on the first INSERT (no prior state). */
    private Integer team2PointsOld;

    /** Team 1 score after the change. NOT NULL. */
    private int team1PointsNew;

    /** Team 2 score after the change. NOT NULL. */
    private int team2PointsNew;

    /** {@link SetState} legacy code before the change. {@code null} on first INSERT. */
    private Integer setStateOld;

    /** {@link SetState} legacy code after the change. NOT NULL. */
    private int setStateNew;

    /**
     * Identity of the actor who made the change (organiser ID, username, etc.). {@code null} in
     * default-tenant LAN mode where no login is required.
     */
    private String actorId;

    /**
     * Optional human-readable reason for the correction, provided by the organiser. {@code null} if
     * no reason was given.
     */
    private String reason;

    /**
     * Timestamp when the change was recorded. Set by the database via DEFAULT CURRENT_TIMESTAMP.
     */
    private LocalDateTime changedAt;

    /**
     * Source type of this audit entry (E06S06, AC8). Values: {@code "TABLET"} (scoring tablet),
     * {@code "ADMIN"} (admin UI correction), or {@code null} for legacy rows written before E06S06.
     *
     * @see SetResultInput#SOURCE_TYPE_TABLET
     * @see SetResultInput#SOURCE_TYPE_ADMIN
     */
    private String sourceType;

    /**
     * Device UUID string when {@code sourceType} is {@code "TABLET"} (E06S06, AC8). {@code null}
     * for admin corrections and legacy rows. Value is {@code device.id.toString()} — the UUID
     * primary key of the device row.
     */
    private String sourceDeviceId;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public AuditLogEntry() {}

    /**
     * Full constructor for programmatic creation by the cascade service (E03S11, E06S06).
     *
     * @param id surrogate primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId tenant scope (NOT NULL)
     * @param matchId match FK (NOT NULL)
     * @param setIndex set index within the match
     * @param team1PointsOld old team 1 score ({@code null} on first insert)
     * @param team2PointsOld old team 2 score ({@code null} on first insert)
     * @param team1PointsNew new team 1 score (NOT NULL)
     * @param team2PointsNew new team 2 score (NOT NULL)
     * @param setStateOld old set state legacy code ({@code null} on first insert)
     * @param setStateNew new set state legacy code (NOT NULL)
     * @param actorId identity of the actor ({@code null} in LAN mode)
     * @param reason optional organiser-provided reason ({@code null} if absent)
     * @param changedAt change timestamp (may be null; DB sets default)
     * @param sourceType audit source type ({@code "TABLET"}, {@code "ADMIN"}, or {@code null})
     * @param sourceDeviceId device UUID string when sourceType is TABLET; {@code null} otherwise
     */
    public AuditLogEntry(
            UUID id,
            UUID tenantId,
            UUID matchId,
            int setIndex,
            Integer team1PointsOld,
            Integer team2PointsOld,
            int team1PointsNew,
            int team2PointsNew,
            Integer setStateOld,
            int setStateNew,
            String actorId,
            String reason,
            LocalDateTime changedAt,
            String sourceType,
            String sourceDeviceId) {
        this.id = id;
        this.tenantId = tenantId;
        this.matchId = matchId;
        this.setIndex = setIndex;
        this.team1PointsOld = team1PointsOld;
        this.team2PointsOld = team2PointsOld;
        this.team1PointsNew = team1PointsNew;
        this.team2PointsNew = team2PointsNew;
        this.setStateOld = setStateOld;
        this.setStateNew = setStateNew;
        this.actorId = actorId;
        this.reason = reason;
        this.changedAt = changedAt;
        this.sourceType = sourceType;
        this.sourceDeviceId = sourceDeviceId;
    }

    // -----------------------------------------------------------------------
    // Type-safe SetState convenience methods
    // -----------------------------------------------------------------------

    /**
     * Returns the old set state as a {@link SetState} enum, or {@code null} if no prior state
     * exists (first INSERT).
     *
     * @return the old state, or {@code null}
     */
    public SetState getSetStateOldAsEnum() {
        return setStateOld == null ? null : SetState.fromLegacyCode(setStateOld);
    }

    /**
     * Returns the new set state as a {@link SetState} enum.
     *
     * @return the new state (never {@code null})
     */
    public SetState getSetStateNewAsEnum() {
        return SetState.fromLegacyCode(setStateNew);
    }

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    public UUID getMatchId() {
        return matchId;
    }

    public void setMatchId(UUID matchId) {
        this.matchId = matchId;
    }

    public int getSetIndex() {
        return setIndex;
    }

    public void setSetIndex(int setIndex) {
        this.setIndex = setIndex;
    }

    public Integer getTeam1PointsOld() {
        return team1PointsOld;
    }

    public void setTeam1PointsOld(Integer team1PointsOld) {
        this.team1PointsOld = team1PointsOld;
    }

    public Integer getTeam2PointsOld() {
        return team2PointsOld;
    }

    public void setTeam2PointsOld(Integer team2PointsOld) {
        this.team2PointsOld = team2PointsOld;
    }

    public int getTeam1PointsNew() {
        return team1PointsNew;
    }

    public void setTeam1PointsNew(int team1PointsNew) {
        this.team1PointsNew = team1PointsNew;
    }

    public int getTeam2PointsNew() {
        return team2PointsNew;
    }

    public void setTeam2PointsNew(int team2PointsNew) {
        this.team2PointsNew = team2PointsNew;
    }

    public Integer getSetStateOld() {
        return setStateOld;
    }

    public void setSetStateOld(Integer setStateOld) {
        this.setStateOld = setStateOld;
    }

    public int getSetStateNew() {
        return setStateNew;
    }

    public void setSetStateNew(int setStateNew) {
        this.setStateNew = setStateNew;
    }

    public String getActorId() {
        return actorId;
    }

    public void setActorId(String actorId) {
        this.actorId = actorId;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public LocalDateTime getChangedAt() {
        return changedAt;
    }

    public void setChangedAt(LocalDateTime changedAt) {
        this.changedAt = changedAt;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getSourceDeviceId() {
        return sourceDeviceId;
    }

    public void setSourceDeviceId(String sourceDeviceId) {
        this.sourceDeviceId = sourceDeviceId;
    }

    @Override
    public String toString() {
        return "AuditLogEntry{id="
                + id
                + ", matchId="
                + matchId
                + ", setIndex="
                + setIndex
                + ", setStateOld="
                + setStateOld
                + ", setStateNew="
                + setStateNew
                + ", sourceType="
                + sourceType
                + ", changedAt="
                + changedAt
                + '}';
    }
}
