package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code devices} table.
 *
 * <p>A {@code Device} represents a scoring tablet (or future display device) that has
 * registered itself with the Tournament Manager. Registration is PIN-based: the tablet
 * opens a known URL, receives a short numeric PIN ({@link #pin}) and an opaque
 * cryptographically random device token ({@link #deviceToken}). The organizer uses the
 * PIN from the admin UI (E06S05) to assign the device to a court field.
 *
 * <h2>Tenant and location scope (DEC-5, DEC-17)</h2>
 * <p>Both {@code tenant_id} and {@code location_id} are NOT NULL from day 1. In V1
 * default-tenant-LAN mode these are resolved from the active request context; the schema
 * is already multi-tenant ready.
 *
 * <h2>Status lifecycle</h2>
 * <ul>
 *   <li>{@code REGISTERED} — device registered; no court assigned yet</li>
 *   <li>{@code ASSIGNED}   — device assigned to a court field</li>
 *   <li>{@code DISCONNECTED} — device has not been seen for an extended period (future use)</li>
 * </ul>
 *
 * <h2>Security (AC11)</h2>
 * <p>The {@link #deviceToken} is a {@link UUID#randomUUID()} string — cryptographically
 * random, not guessable. The {@link #pin} is a short numeric string for human convenience
 * (assignment UI), not a security token.
 *
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E06S03.story.md">Story E06S03</a>
 */
@Table("devices")
public class Device {

    /** Primary key — UUID generated by the application layer. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every device belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Location scope — NOT NULL per DEC-5, DEC-17. Devices are scoped to a location.
     * Foreign key references {@code locations(id)}.
     */
    private UUID locationId;

    /**
     * Opaque device token — cryptographically random UUID string (AC11).
     * Used by the tablet to identify itself on all subsequent API calls.
     * Unique across the entire system (UNIQUE constraint on column).
     */
    private String deviceToken;

    /**
     * Short numeric PIN — unique within tenant while the device row exists (AC7).
     * Human-readable assignment code only; not a security credential.
     * 4–6 digits; avoids trivially confusable sequences.
     */
    private String pin;

    /**
     * Device type — defaults to {@code SCORING_TABLET}. E07 will introduce {@code DISPLAY}.
     * Stored as VARCHAR enum name.
     */
    private String deviceType;

    /**
     * Assigned court field number — null if unassigned (AC5).
     * Set by the organizer via the admin UI (E06S05) after looking up the device by PIN.
     */
    private Integer assignedField;

    /**
     * Device lifecycle status — {@code REGISTERED}, {@code ASSIGNED}, {@code DISCONNECTED}.
     * Defaults to {@code REGISTERED} at the schema level.
     */
    private String status;

    /**
     * Timestamp when the device first registered.
     * Set by the database via {@code DEFAULT CURRENT_TIMESTAMP}.
     */
    private LocalDateTime registeredAt;

    /**
     * Timestamp of the device's last heartbeat or API call (future use).
     * Null until the device sends its first keepalive request.
     */
    private LocalDateTime lastSeenAt;

    // -------------------------------------------------------------------------
    // Status constants
    // -------------------------------------------------------------------------

    public static final String STATUS_REGISTERED    = "REGISTERED";
    public static final String STATUS_ASSIGNED      = "ASSIGNED";
    public static final String STATUS_DISCONNECTED  = "DISCONNECTED";

    /** Default device type for E06 scoring tablets. */
    public static final String TYPE_SCORING_TABLET  = "SCORING_TABLET";

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Device() {
    }

    /**
     * Full constructor for programmatic creation.
     *
     * @param id            primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId      tenant scope (NOT NULL)
     * @param locationId    location scope (NOT NULL)
     * @param deviceToken   opaque auth token (cryptographically random)
     * @param pin           short numeric PIN (unique within tenant)
     * @param deviceType    device type enum name (e.g., {@code SCORING_TABLET})
     * @param assignedField assigned court field number (null = unassigned)
     * @param status        lifecycle status
     * @param registeredAt  registration timestamp (may be null — DB sets default)
     * @param lastSeenAt    last-seen timestamp (null until first heartbeat)
     */
    public Device(UUID id, UUID tenantId, UUID locationId, String deviceToken, String pin,
                  String deviceType, Integer assignedField, String status,
                  LocalDateTime registeredAt, LocalDateTime lastSeenAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.locationId = locationId;
        this.deviceToken = deviceToken;
        this.pin = pin;
        this.deviceType = deviceType;
        this.assignedField = assignedField;
        this.status = status;
        this.registeredAt = registeredAt;
        this.lastSeenAt = lastSeenAt;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getLocationId() { return locationId; }
    public void setLocationId(UUID locationId) { this.locationId = locationId; }

    public String getDeviceToken() { return deviceToken; }
    public void setDeviceToken(String deviceToken) { this.deviceToken = deviceToken; }

    public String getPin() { return pin; }
    public void setPin(String pin) { this.pin = pin; }

    public String getDeviceType() { return deviceType; }
    public void setDeviceType(String deviceType) { this.deviceType = deviceType; }

    public Integer getAssignedField() { return assignedField; }
    public void setAssignedField(Integer assignedField) { this.assignedField = assignedField; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getRegisteredAt() { return registeredAt; }
    public void setRegisteredAt(LocalDateTime registeredAt) { this.registeredAt = registeredAt; }

    public LocalDateTime getLastSeenAt() { return lastSeenAt; }
    public void setLastSeenAt(LocalDateTime lastSeenAt) { this.lastSeenAt = lastSeenAt; }
}
