package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code devices} table.
 *
 * <p>A {@code Device} represents a hardware device registered with the Tournament Manager.
 * Two device types are supported:
 * <ul>
 *   <li><b>Scoring tablets</b> (E06S03): register via URL, receive a short numeric PIN
 *       ({@link #pin}) and an opaque device token ({@link #deviceToken}). The organizer
 *       assigns the tablet to a court using the PIN from the admin UI.</li>
 *   <li><b>Display devices</b> (E07S01+): register via URL; no PIN ({@link #pin} is null).
 *       Identified by a human-readable {@link #deviceName}. Behaviour controlled by
 *       {@link #configuration} (JSON string, e.g. {@code {"display_schema":"OVERVIEW"}}).</li>
 * </ul>
 *
 * <h2>Tenant and location scope (DEC-5, DEC-17, DEC-24)</h2>
 * <p>{@code tenant_id} is NOT NULL — every device belongs to exactly one tenant from registration.
 * {@code location_id} is <b>nullable</b> (DEC-24 device-model carve-out, 2026-04-18): a null
 * value means "registered but not yet assigned to a venue location". Devices are assigned to
 * a location in a separate admin action after registration.
 *
 * <h2>Status lifecycle</h2>
 * <ul>
 *   <li>{@code REGISTERED} — device registered; no court assigned yet</li>
 *   <li>{@code ASSIGNED}   — device assigned to a court field</li>
 *   <li>{@code DISCONNECTED} — device has not been seen for an extended period (future use)</li>
 * </ul>
 *
 * <h2>Security</h2>
 * <p>The {@link #deviceToken} is a {@link UUID#randomUUID()} string — cryptographically
 * random, not guessable. The {@link #pin} (scoring tablets only) is a short numeric string
 * for human convenience; it is not a security credential.
 *
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E06S03.story.md">Story E06S03</a>
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E07S01.story.md">Story E07S01</a>
 */
@Table("devices")
public class Device {

    /** Primary key — UUID generated by the application layer. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every device belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Location scope — nullable per DEC-24 (2026-04-18 device-model carve-out from DEC-17).
     *
     * <p>A {@code null} value means the device is in the "registered but not yet assigned to a
     * location" state. This is a valid intermediate state in the two-phase device lifecycle:
     * (1) admin registers the device and receives a device_token; (2) admin assigns the device
     * to a specific venue location via {@code POST /api/admin/devices/{id}/location/{locationId}}.
     *
     * <p>When non-null, the value is a foreign key referencing {@code locations(id)}.
     *
     * <p><b>Usage constraint (DEC-24 D1):</b>
     * <ul>
     *   <li>SCORING_TABLET devices cannot open a scoring session while {@code locationId} is null —
     *       rejected at the domain-service boundary with a typed exception.</li>
     *   <li>DISPLAY devices may operate while unassigned — the server returns an overview-mode payload.</li>
     * </ul>
     */
    private UUID locationId;

    /**
     * Opaque device token — cryptographically random UUID string (AC11).
     * Used by the tablet to identify itself on all subsequent API calls.
     * Unique across the entire system (UNIQUE constraint on column).
     */
    private String deviceToken;

    /**
     * Short numeric PIN — unique within tenant while the device row exists (scoring tablets only).
     * Null for display devices, which register via URL without a PIN (E07S01 AC1).
     * Human-readable assignment code only; not a security credential.
     * 4–6 digits; avoids trivially confusable sequences.
     */
    private String pin;

    /**
     * Device type — defaults to {@code SCORING_TABLET}. E07 will introduce {@code DISPLAY}.
     * Stored as VARCHAR enum name.
     */
    private String deviceType;

    /**
     * Assigned court field number — null if unassigned (AC5).
     * Set by the organizer via the admin UI (E06S05) after looking up the device by PIN.
     */
    private Integer assignedField;

    /**
     * Device lifecycle status — {@code REGISTERED}, {@code ASSIGNED}, {@code DISCONNECTED}.
     * Defaults to {@code REGISTERED} at the schema level.
     */
    private String status;

    /**
     * Timestamp when the device first registered.
     * Set by the database via {@code DEFAULT CURRENT_TIMESTAMP}.
     */
    private LocalDateTime registeredAt;

    /**
     * Timestamp of the device's last heartbeat or API call (future use).
     * Null until the device sends its first keepalive request.
     */
    private LocalDateTime lastSeenAt;

    /**
     * Human-readable device name — used for display devices (E07S01 AC2).
     * Null for scoring tablets; set by the admin when managing display devices.
     * Maps to {@code device_name} column (VARCHAR 255, nullable).
     */
    private String deviceName;

    /**
     * JSON configuration string — controls what the device displays (E07S01 AC2, AC5).
     * Null for scoring tablets. For display devices in V1, expected shape:
     * {@code {"display_schema":"OVERVIEW"}}.
     * Stored as TEXT per DEC-14 (H2 compatibility — no database-level JSON type).
     * Application-layer parsing uses Jackson; no DB-level JSON schema validation.
     */
    private String configuration;

    // -------------------------------------------------------------------------
    // Status constants
    // -------------------------------------------------------------------------

    public static final String STATUS_REGISTERED    = "REGISTERED";
    public static final String STATUS_ASSIGNED      = "ASSIGNED";
    public static final String STATUS_DISCONNECTED  = "DISCONNECTED";

    /** Device type for E06 scoring tablets. */
    public static final String TYPE_SCORING_TABLET  = "SCORING_TABLET";

    /** Device type for E07+ display devices (Gesamtübersicht and future display modes). */
    public static final String TYPE_DISPLAY         = "DISPLAY";

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Device() {
    }

    /**
     * Full constructor for programmatic creation.
     *
     * @param id            primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId      tenant scope (NOT NULL)
     * @param locationId    location scope — nullable (DEC-24); null means "registered, not yet assigned"
     * @param deviceToken   opaque auth token (cryptographically random)
     * @param pin           short numeric PIN (unique within tenant; null for display devices)
     * @param deviceType    device type enum name (e.g., {@code SCORING_TABLET}, {@code DISPLAY})
     * @param assignedField assigned court field number (null = unassigned)
     * @param status        lifecycle status
     * @param registeredAt  registration timestamp (may be null — DB sets default)
     * @param lastSeenAt    last-seen timestamp (null until first heartbeat)
     * @param deviceName    human-readable device name (null for scoring tablets)
     * @param configuration JSON configuration string (null for scoring tablets)
     */
    public Device(UUID id, UUID tenantId, UUID locationId, String deviceToken, String pin,
                  String deviceType, Integer assignedField, String status,
                  LocalDateTime registeredAt, LocalDateTime lastSeenAt,
                  String deviceName, String configuration) {
        this.id = id;
        this.tenantId = tenantId;
        this.locationId = locationId;
        this.deviceToken = deviceToken;
        this.pin = pin;
        this.deviceType = deviceType;
        this.assignedField = assignedField;
        this.status = status;
        this.registeredAt = registeredAt;
        this.lastSeenAt = lastSeenAt;
        this.deviceName = deviceName;
        this.configuration = configuration;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getLocationId() { return locationId; }
    public void setLocationId(UUID locationId) { this.locationId = locationId; }

    public String getDeviceToken() { return deviceToken; }
    public void setDeviceToken(String deviceToken) { this.deviceToken = deviceToken; }

    public String getPin() { return pin; }
    public void setPin(String pin) { this.pin = pin; }

    public String getDeviceType() { return deviceType; }
    public void setDeviceType(String deviceType) { this.deviceType = deviceType; }

    public Integer getAssignedField() { return assignedField; }
    public void setAssignedField(Integer assignedField) { this.assignedField = assignedField; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getRegisteredAt() { return registeredAt; }
    public void setRegisteredAt(LocalDateTime registeredAt) { this.registeredAt = registeredAt; }

    public LocalDateTime getLastSeenAt() { return lastSeenAt; }
    public void setLastSeenAt(LocalDateTime lastSeenAt) { this.lastSeenAt = lastSeenAt; }

    public String getDeviceName() { return deviceName; }
    public void setDeviceName(String deviceName) { this.deviceName = deviceName; }

    public String getConfiguration() { return configuration; }
    public void setConfiguration(String configuration) { this.configuration = configuration; }
}
