package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code match} table.
 *
 * <p>A Match is the central operational entity of the tournament domain. It pairs two
 * {@link TeamAvatar} instances within a phase and tracks the match lifecycle from creation
 * through slot-optimization to result recording.
 *
 * <h2>Tenant scope (DEC-5, DEC-17)</h2>
 * <p>{@code tenantId} is NOT NULL — every match belongs to exactly one tenant.
 * FK references {@code tenants(id)}.
 *
 * <h2>TeamAvatar references (DEC-9)</h2>
 * <p>{@code memberAvatar1Id} and {@code memberAvatar2Id} reference {@link TeamAvatar} rows,
 * not {@link Team} rows directly. The avatar is the team's appearance in a specific
 * phase/group, which is the correct granularity for match pairings.
 *
 * <h2>Match state (AC7)</h2>
 * <p>The {@code state} column stores the legacy integer code from {@link MatchState}.
 * Use {@link #getMatchState()} and {@link #setMatchState(MatchState)} for type-safe access.
 * State transitions are owned by the cascade service (E03S11).
 *
 * <h2>Slot coordinates (AC3)</h2>
 * <p>{@code lapNumber} and {@code fieldNumber} are nullable. A freshly generated match has
 * these {@code null}. E04's slot-optimization client fills them via UPDATE. The cascade
 * service expects non-null slot coordinates before transitioning beyond {@code OPEN} state.
 *
 * <h2>Referee columns (AC4)</h2>
 * <p>{@code refereeTeamId}, {@code refereeDescription}, and {@code refereePreferenceConfig}
 * are all nullable. The {@link RefereeAssigner} service (E03S10) populates them.
 * {@code refereePreferenceConfig} is stored as a CLOB (H2 JSONB equivalent); the serialization
 * format is specified in E03S10.
 *
 * @see MatchState
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S02.story.md">Story E03S02</a>
 */
@Table("match")
public class Match {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every match belongs to exactly one tenant.
     * FK references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Tournament this match belongs to. NOT NULL.
     * FK references {@code tournament(id)}.
     */
    private UUID tournamentId;

    /**
     * Phase this match is part of. NOT NULL.
     * FK references {@code phase(id)}.
     */
    private UUID phaseId;

    /**
     * First team in the match pairing — references a {@link TeamAvatar} (DEC-9).
     * NOT NULL. FK references {@code team_avatar(id)}.
     * Explicit {@code @Column} required because Spring Data JDBC converts {@code memberAvatar1Id}
     * to {@code member_avatar1_id} but the DB column is {@code member_avatar_1_id}.
     */
    @Column("member_avatar_1_id")
    private UUID memberAvatar1Id;

    /**
     * Second team in the match pairing — references a {@link TeamAvatar} (DEC-9).
     * NOT NULL. FK references {@code team_avatar(id)}.
     * Explicit {@code @Column} required (see {@code memberAvatar1Id}).
     */
    @Column("member_avatar_2_id")
    private UUID memberAvatar2Id;

    /**
     * Match lifecycle state stored as legacy integer code.
     * Valid values: 0 (OPEN), 10 (ENABLED), 30 (INPROGRESS), 35 (ONCHECK),
     * 50 (FINISHED_STANDOFF), 51 (FINISHED_WINNER1), 52 (FINISHED_WINNER2), -10 (CANCELED).
     * Use {@link #getMatchState()} and {@link #setMatchState(MatchState)} for type-safe access.
     * Schema-level CHECK constraint enforces valid values (AC5).
     */
    private int state;

    /**
     * Maximum number of sets for this match, derived from the tournament's
     * {@link MatchFormat#getMaxSets()} at match generation time (D-30).
     * Kept as a per-match column for future multi-format flexibility (legacy convention).
     * Defaults to 1 at the schema level; must be set correctly at insert time.
     */
    private int setLimit;

    /**
     * Lap (round) number assigned by E04 slot-optimization. {@code null} until
     * slot-optimization runs — represents "not yet scheduled" (AC3, D-19).
     */
    private Integer lapNumber;

    /**
     * Field number assigned by E04 slot-optimization. {@code null} until
     * slot-optimization runs — represents "not yet scheduled" (AC3, D-23).
     */
    private Integer fieldNumber;

    /**
     * UUID of the team assigned to referee this match. {@code null} until
     * {@link RefereeAssigner} (E03S10) populates it.
     * FK references {@code team(id)} (the team entity, not its avatar — AC4).
     */
    private UUID refereeTeamId;

    /**
     * Free-text description or manual override notes for the referee assignment.
     * {@code null} when not set (AC4).
     */
    private String refereeDescription;

    /**
     * JSON preference rules for automatic referee assignment.
     * Stored as CLOB (H2 JSONB equivalent). Serialization format specified in E03S10.
     * {@code null} when no preferences are configured (AC4).
     */
    private String refereePreferenceConfig;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Match() {
    }

    /**
     * Full constructor for programmatic creation (e.g., by the MatchGenerator).
     *
     * @param id                       primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId                 tenant scope (NOT NULL)
     * @param tournamentId             tournament FK (NOT NULL)
     * @param phaseId                  phase FK (NOT NULL)
     * @param memberAvatar1Id          first team avatar FK (NOT NULL)
     * @param memberAvatar2Id          second team avatar FK (NOT NULL)
     * @param state                    legacy int state code (use {@link MatchState#getLegacyCode()})
     * @param setLimit                 max sets derived from MatchFormat.maxSets
     * @param lapNumber                slot lap — {@code null} until slot-optimization
     * @param fieldNumber              slot field — {@code null} until slot-optimization
     * @param refereeTeamId            referee team — {@code null} until RefereeAssigner runs
     * @param refereeDescription       free-text referee notes — may be {@code null}
     * @param refereePreferenceConfig  JSON preference rules — may be {@code null}
     * @param createdAt                creation timestamp (may be null; DB sets default)
     */
    public Match(UUID id, UUID tenantId, UUID tournamentId, UUID phaseId,
                 UUID memberAvatar1Id, UUID memberAvatar2Id,
                 int state, int setLimit,
                 Integer lapNumber, Integer fieldNumber,
                 UUID refereeTeamId, String refereeDescription, String refereePreferenceConfig,
                 LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.tournamentId = tournamentId;
        this.phaseId = phaseId;
        this.memberAvatar1Id = memberAvatar1Id;
        this.memberAvatar2Id = memberAvatar2Id;
        this.state = state;
        this.setLimit = setLimit;
        this.lapNumber = lapNumber;
        this.fieldNumber = fieldNumber;
        this.refereeTeamId = refereeTeamId;
        this.refereeDescription = refereeDescription;
        this.refereePreferenceConfig = refereePreferenceConfig;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Type-safe MatchState convenience methods
    // -------------------------------------------------------------------------

    /**
     * Returns the match lifecycle state as the {@link MatchState} enum.
     *
     * @return the current state
     * @throws IllegalArgumentException if the stored integer code is unknown (data corruption guard)
     */
    public MatchState getMatchState() {
        return MatchState.fromLegacyCode(this.state);
    }

    /**
     * Sets the match lifecycle state from a {@link MatchState} enum value.
     * Stores the corresponding legacy integer code in {@link #state}.
     *
     * @param matchState the new state (must not be {@code null})
     * @throws NullPointerException if {@code matchState} is {@code null}
     */
    public void setMatchState(MatchState matchState) {
        if (matchState == null) {
            throw new NullPointerException("matchState must not be null");
        }
        this.state = matchState.getLegacyCode();
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getTournamentId() { return tournamentId; }
    public void setTournamentId(UUID tournamentId) { this.tournamentId = tournamentId; }

    public UUID getPhaseId() { return phaseId; }
    public void setPhaseId(UUID phaseId) { this.phaseId = phaseId; }

    public UUID getMemberAvatar1Id() { return memberAvatar1Id; }
    public void setMemberAvatar1Id(UUID memberAvatar1Id) { this.memberAvatar1Id = memberAvatar1Id; }

    public UUID getMemberAvatar2Id() { return memberAvatar2Id; }
    public void setMemberAvatar2Id(UUID memberAvatar2Id) { this.memberAvatar2Id = memberAvatar2Id; }

    public int getState() { return state; }
    public void setState(int state) { this.state = state; }

    public int getSetLimit() { return setLimit; }
    public void setSetLimit(int setLimit) { this.setLimit = setLimit; }

    public Integer getLapNumber() { return lapNumber; }
    public void setLapNumber(Integer lapNumber) { this.lapNumber = lapNumber; }

    public Integer getFieldNumber() { return fieldNumber; }
    public void setFieldNumber(Integer fieldNumber) { this.fieldNumber = fieldNumber; }

    public UUID getRefereeTeamId() { return refereeTeamId; }
    public void setRefereeTeamId(UUID refereeTeamId) { this.refereeTeamId = refereeTeamId; }

    public String getRefereeDescription() { return refereeDescription; }
    public void setRefereeDescription(String refereeDescription) { this.refereeDescription = refereeDescription; }

    public String getRefereePreferenceConfig() { return refereePreferenceConfig; }
    public void setRefereePreferenceConfig(String refereePreferenceConfig) { this.refereePreferenceConfig = refereePreferenceConfig; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
