package de.vvwt.tm.domain;

import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Spring Data JDBC entity for the {@code phase_breaks} table.
 *
 * <p>A {@code PhaseBreak} represents a pause that occurs within a phase at a specific lap boundary.
 * For example, {@code afterLapNumber=4, durationMinutes=40} means a 40-minute break between round 4
 * and round 5 of the phase. This does NOT create additional lap entities or change any match-to-lap
 * assignments — it only affects the timeline calculation in E08S03.
 *
 * <p>The {@code label} field is a free-text organizer-entered string (e.g., "Mittagspause",
 * "Siegerehrung Vorrunde") that appears on the Laufzettel. If null, the Laufzettel renders a
 * generic "Pause" label.
 *
 * <p>Tenant scope is enforced per DEC-5 / DEC-17: {@code tenantId} is NOT NULL and carries a
 * foreign key reference to {@code tenants(id)}. All repository operations are tenant-scoped via
 * {@link de.vvwt.tm.domain.repo.TenantScopedRepository}.
 *
 * <p>The schema-level UNIQUE constraint on {@code (phase_id, after_lap_number)} ensures at most one
 * break per lap boundary per phase (AC2). The application-layer {@link PhaseBreakService} checks
 * this before persisting (AC6).
 *
 * @see PhaseBreakService
 * @see de.vvwt.tm.domain.repo.PhaseBreakRepository
 * @see <a
 *     href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E08S01.story.md">Story
 *     E08S01</a>
 */
@Table("phase_breaks")
public class PhaseBreak {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every phase break belongs to exactly one tenant. Foreign
     * key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Parent phase — NOT NULL. Foreign key references {@code phase(id)}. A phase break always
     * belongs to exactly one phase.
     */
    private UUID phaseId;

    /**
     * The lap number after which this break occurs.
     *
     * <p>A value of {@code 4} means the break occurs in the timeline after lap 4 ends and before
     * lap 5 begins. Must be ≥ 1 and < totalLaps in the phase (validated by {@link
     * PhaseBreakService} — AC5).
     */
    private int afterLapNumber;

    /**
     * Duration of the break in minutes. Must be > 0 (enforced by schema CHECK constraint and
     * validated by {@link PhaseBreakService}).
     */
    private int durationMinutes;

    /**
     * Optional organizer-entered display label for the break (e.g., "Mittagspause"). If null, the
     * Laufzettel renders a generic "Pause" label.
     */
    private String label;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public PhaseBreak() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId tenant scope (NOT NULL — DEC-17)
     * @param phaseId parent phase (NOT NULL)
     * @param afterLapNumber lap number after which the break occurs (≥ 1, < totalLaps)
     * @param durationMinutes break duration in minutes (> 0)
     * @param label optional display label for the break (may be null)
     */
    public PhaseBreak(
            UUID id,
            UUID tenantId,
            UUID phaseId,
            int afterLapNumber,
            int durationMinutes,
            String label) {
        this.id = id;
        this.tenantId = tenantId;
        this.phaseId = phaseId;
        this.afterLapNumber = afterLapNumber;
        this.durationMinutes = durationMinutes;
        this.label = label;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    public UUID getPhaseId() {
        return phaseId;
    }

    public void setPhaseId(UUID phaseId) {
        this.phaseId = phaseId;
    }

    public int getAfterLapNumber() {
        return afterLapNumber;
    }

    public void setAfterLapNumber(int afterLapNumber) {
        this.afterLapNumber = afterLapNumber;
    }

    public int getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }
}
