package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code phase_audit_log} table (E05S07, AC5).
 *
 * <p>Records phase-level governance actions taken by an organiser. The only action type in V1 is
 * {@code FORCE_ADVANCE_LAP} — written when an organiser forces the lap counter forward despite
 * unfinished matches in the current lap.
 *
 * <h2>Append-only convention</h2>
 * <p>The {@code phase_audit_log} table is append-only by convention. The repository layer
 * ({@link de.vvwt.tm.domain.repo.PhaseAuditLogRepository}) explicitly forbids
 * {@code UPDATE} and {@code DELETE} operations — identical to the {@code audit_log} pattern.
 *
 * <h2>Tenant scope (DEC-5, DEC-17)</h2>
 * <p>{@code tenantId} is NOT NULL — every entry belongs to exactly one tenant.
 *
 * @see de.vvwt.tm.domain.repo.PhaseAuditLogRepository
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E05S07.story.md">Story E05S07</a>
 */
@Table("phase_audit_log")
public class PhaseAuditLogEntry {

    /** Surrogate primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Phase this entry belongs to — NOT NULL.
     * Foreign key references {@code phase(id)}.
     */
    private UUID phaseId;

    /**
     * String identifier for the governance action taken.
     * Valid value in V1: {@code "FORCE_ADVANCE_LAP"}.
     */
    private String action;

    /**
     * Lap number at the time of the action.
     * For {@code FORCE_ADVANCE_LAP}: the lap being forced past (before increment).
     */
    private int lapNumber;

    /**
     * Count of unfinished matches in the current lap at the time of the forced advance (AC5).
     * Always {@code ≥ 0}; enforced by a schema-level {@code CHECK} constraint.
     */
    private int unfinishedMatchCount;

    /**
     * Identity of the organiser who performed the action (username, ID, etc.).
     * {@code null} in default-tenant LAN mode where no login is required (DEC-5).
     */
    private String actorId;

    /** Timestamp when the action was recorded. Set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime changedAt;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public PhaseAuditLogEntry() {
    }

    /**
     * Full constructor for programmatic creation.
     *
     * @param id                   surrogate primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId             tenant scope (NOT NULL)
     * @param phaseId              phase FK (NOT NULL)
     * @param action               governance action identifier (NOT NULL)
     * @param lapNumber            lap number at the time of the action (≥ 0)
     * @param unfinishedMatchCount count of unfinished matches (≥ 0)
     * @param actorId              identity of the actor ({@code null} in LAN mode)
     * @param changedAt            change timestamp (may be null; DB sets default)
     */
    public PhaseAuditLogEntry(UUID id, UUID tenantId, UUID phaseId,
                               String action, int lapNumber, int unfinishedMatchCount,
                               String actorId, LocalDateTime changedAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.phaseId = phaseId;
        this.action = action;
        this.lapNumber = lapNumber;
        this.unfinishedMatchCount = unfinishedMatchCount;
        this.actorId = actorId;
        this.changedAt = changedAt;
    }

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getPhaseId() { return phaseId; }
    public void setPhaseId(UUID phaseId) { this.phaseId = phaseId; }

    public String getAction() { return action; }
    public void setAction(String action) { this.action = action; }

    public int getLapNumber() { return lapNumber; }
    public void setLapNumber(int lapNumber) { this.lapNumber = lapNumber; }

    public int getUnfinishedMatchCount() { return unfinishedMatchCount; }
    public void setUnfinishedMatchCount(int unfinishedMatchCount) { this.unfinishedMatchCount = unfinishedMatchCount; }

    public String getActorId() { return actorId; }
    public void setActorId(String actorId) { this.actorId = actorId; }

    public LocalDateTime getChangedAt() { return changedAt; }
    public void setChangedAt(LocalDateTime changedAt) { this.changedAt = changedAt; }

    @Override
    public String toString() {
        return "PhaseAuditLogEntry{id=" + id
                + ", phaseId=" + phaseId
                + ", action='" + action + '\''
                + ", lapNumber=" + lapNumber
                + ", unfinishedMatchCount=" + unfinishedMatchCount
                + ", changedAt=" + changedAt + '}';
    }
}
