package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code phase} table.
 *
 * <p>A {@code Phase} represents one stage within a {@link Tournament} (e.g., preliminary round,
 * finals). Phases are first-class entities per D-18 and D-35. Each tournament may have one or
 * more phases, ordered by {@code sequenceNumber}.
 *
 * <p>The unique constraint on {@code (tournamentId, sequenceNumber)} in the schema ensures
 * unambiguous ordering within a tournament.
 *
 * <p>Phase lifecycle status values (stored as VARCHAR):
 * <ul>
 *   <li>{@link PhaseStatus#PENDING}   — created; not yet started</li>
 *   <li>{@link PhaseStatus#ACTIVE}    — currently in progress</li>
 *   <li>{@link PhaseStatus#COMPLETED} — all matches in this phase are finished</li>
 * </ul>
 *
 * <p>The {@code currentLapNumber} advances during cascade recompute per D-21 step 10.
 * It starts at 0 (no lap has completed yet) and increments as rounds are finalized.
 *
 * <p>The {@code sortType} determines how teams from the previous phase are redistributed into
 * this phase's groups (E05S08). Valid values: {@code team_number}, {@code placement_group},
 * {@code group_placement}. Persisted on the phase row so the mapping service can retrieve it
 * after the draft JSON is cleared (V10 migration). Phase 1 always uses {@code team_number}
 * effectively — the column exists on Phase 1 rows but its value is not used for mapping
 * (there is no previous phase to map from).
 *
 * @see Tournament
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S01.story.md">Story E03S01</a>
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E05S08.story.md">Story E05S08</a>
 */
@Table("phase")
public class Phase {

    /**
     * Lifecycle status for a phase.
     *
     * <p>Stored as a VARCHAR in the database (the enum name). The persistence layer stores and
     * reads this as a String; the domain layer works with the enum for type safety.
     */
    public enum PhaseStatus {
        /** Phase is created but not yet started. */
        PENDING,
        /** Phase is currently in progress (at least one match has been played or is scheduled). */
        ACTIVE,
        /** All matches in this phase have been completed and standings are finalized. */
        COMPLETED
    }

    /** Primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every phase belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Parent tournament — NOT NULL. Foreign key references {@code tournament(id)}.
     * A phase always belongs to exactly one tournament.
     */
    private UUID tournamentId;

    /**
     * Ordering number within the parent tournament. Together with {@code tournamentId},
     * forms a unique pair (schema UNIQUE constraint). Starts at 1 for the first phase.
     */
    private int sequenceNumber;

    /** Human-readable phase label (e.g., "Vorrunde", "Finale"). */
    private String description;

    /**
     * Current lifecycle status of this phase. Stored as the enum name (VARCHAR) in the database.
     * Application code uses {@link PhaseStatus} for type-safe comparisons.
     */
    private String status;

    /**
     * Active lap index within this phase. Starts at 0 (no lap completed). Incremented
     * automatically during cascade recompute at round finalization (D-21 step 10).
     */
    private int currentLapNumber;

    /**
     * How teams from the previous phase are redistributed into this phase's groups (E05S08, V10).
     *
     * <p>Valid values (from {@link de.vvwt.tm.domain.draft.DraftSection#getSortType()}):
     * <ul>
     *   <li>{@code "team_number"}     — teams sorted by team number (Phase 1 default / fallback)</li>
     *   <li>{@code "placement_group"} — sort by (placement_in_group ASC, group_number ASC), round-robin distribution</li>
     *   <li>{@code "group_placement"} — sort by (group_number ASC, placement_in_group ASC), sequential distribution</li>
     * </ul>
     *
     * <p>Persisted so the mapping suggestion endpoint can read it after the draft JSON is cleared.
     * NOT NULL — V10 migration sets DEFAULT 'team_number' for existing rows.
     */
    private String sortType;

    /**
     * Number of groups configured for this phase (E05S08, V10).
     *
     * <p>Persisted so the mapping suggestion endpoint can know how many target groups exist
     * for a Phase 2+ without relying on the draft JSON (which is cleared after apply).
     * NOT NULL — V10 migration sets DEFAULT 1 for existing Phase 1 rows.
     */
    private int groupCount;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Phase() {
    }

    /**
     * Full constructor for programmatic creation (E05S08 — includes sortType and groupCount).
     *
     * @param id               primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId         tenant scope (NOT NULL)
     * @param tournamentId     parent tournament (NOT NULL)
     * @param sequenceNumber   ordering within the tournament (≥ 1)
     * @param description      human-readable label (NOT NULL)
     * @param status           lifecycle status name (e.g., {@code "PENDING"})
     * @param currentLapNumber active lap index (≥ 0)
     * @param sortType         how teams enter this phase (e.g., {@code "team_number"}) — E05S08
     * @param groupCount       number of groups configured for this phase (≥ 1) — E05S08
     * @param createdAt        creation timestamp (may be null; DB sets default)
     */
    public Phase(UUID id, UUID tenantId, UUID tournamentId, int sequenceNumber,
                 String description, String status, int currentLapNumber,
                 String sortType, int groupCount, LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.tournamentId = tournamentId;
        this.sequenceNumber = sequenceNumber;
        this.description = description;
        this.status = status;
        this.currentLapNumber = currentLapNumber;
        this.sortType = sortType;
        this.groupCount = groupCount;
        this.createdAt = createdAt;
    }

    /**
     * Legacy constructor for backward compatibility — sets sortType to {@code "team_number"}
     * and groupCount to 1.
     *
     * @deprecated Use the full constructor with {@code sortType} and {@code groupCount} instead.
     */
    @Deprecated
    public Phase(UUID id, UUID tenantId, UUID tournamentId, int sequenceNumber,
                 String description, String status, int currentLapNumber,
                 LocalDateTime createdAt) {
        this(id, tenantId, tournamentId, sequenceNumber, description, status, currentLapNumber,
                "team_number", 1, createdAt);
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getTournamentId() { return tournamentId; }
    public void setTournamentId(UUID tournamentId) { this.tournamentId = tournamentId; }

    public int getSequenceNumber() { return sequenceNumber; }
    public void setSequenceNumber(int sequenceNumber) { this.sequenceNumber = sequenceNumber; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public int getCurrentLapNumber() { return currentLapNumber; }
    public void setCurrentLapNumber(int currentLapNumber) { this.currentLapNumber = currentLapNumber; }

    public String getSortType() { return sortType; }
    public void setSortType(String sortType) { this.sortType = sortType; }

    public int getGroupCount() { return groupCount; }
    public void setGroupCount(int groupCount) { this.groupCount = groupCount; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
