package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code round_snapshots} table (E03S04, AC5, D-2, D-10).
 *
 * <p>A {@code RoundSnapshot} captures the complete standings of a phase at a lap-advance
 * boundary. It is written by the round-end snapshot service (E03S13) after each lap
 * completes and is consumed by:
 * <ul>
 *   <li>E08 (print output) — rehydrates the standings for physical print sheets</li>
 *   <li>E07 (overview UI) — displays historical standings between laps</li>
 * </ul>
 *
 * <h2>Snapshot uniqueness invariant (AC5, AC9)</h2>
 * <p>The schema enforces {@code UNIQUE (tournament_id, phase_id, lap_number)}: exactly one
 * snapshot exists per (tournament, phase, lap) combination. Attempting to INSERT a second
 * snapshot for the same triple fails with a UNIQUE constraint violation. The snapshot service
 * (E03S13) must check for an existing snapshot before writing.
 *
 * <h2>Snapshot payload format</h2>
 * <p>{@code snapshotPayload} is a JSON CLOB for V1 simplicity. The exact JSON schema is a
 * Delivery decision specified in the E03S04 implementation report. For V1 the payload is a
 * serialized standings array sufficient for E08's print output to rehydrate. Post-V1, typed
 * columns may be added in a future migration if richer snapshot queries are needed.
 *
 * <p>Suggested JSON structure (Delivery decision, not a product constraint):
 * <pre>
 * {
 *   "lapNumber": 3,
 *   "generatedAt": "2026-04-12T10:00:00Z",
 *   "standings": [
 *     { "rank": 1, "avatarId": "...", "groupNumber": 1, "groupPosition": 2,
 *       "points": 6, "setsWon": 3, "setsLost": 0,
 *       "setQuotient": 1.7976931348623157E308, "ballQuotient": 2.5,
 *       "isWithoutAssessment": false }
 *   ]
 * }
 * </pre>
 *
 * <h2>Tenant scope (DEC-5, DEC-17)</h2>
 * <p>{@code tenantId} is NOT NULL — every snapshot belongs to exactly one tenant.
 *
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S04.story.md">Story E03S04</a>
 */
@Table("round_snapshots")
public class RoundSnapshot {

    /** Surrogate primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every snapshot belongs to exactly one tenant.
     * FK references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Tournament this snapshot belongs to. NOT NULL.
     * FK references {@code tournament(id)}.
     */
    private UUID tournamentId;

    /**
     * Phase this snapshot covers. NOT NULL.
     * FK references {@code phase(id)}.
     * Together with {@code tournamentId} and {@code lapNumber}, forms the UNIQUE key.
     */
    private UUID phaseId;

    /**
     * The lap (round) number at which this snapshot was taken.
     * Together with {@code tournamentId} and {@code phaseId}, must be unique (schema UNIQUE constraint).
     */
    private int lapNumber;

    /**
     * JSON serialization of the standings at this lap boundary.
     * Stored as CLOB. The exact schema is documented in the E03S04 implementation report.
     * NOT NULL — a snapshot without payload has no meaning.
     */
    private String snapshotPayload;

    /** Timestamp when this snapshot was created. Set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public RoundSnapshot() {
    }

    /**
     * Full constructor for programmatic creation by the round-end snapshot service (E03S13).
     *
     * @param id              surrogate primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId        tenant scope (NOT NULL)
     * @param tournamentId    tournament FK (NOT NULL)
     * @param phaseId         phase FK (NOT NULL)
     * @param lapNumber       lap/round number at snapshot time (&ge; 0)
     * @param snapshotPayload JSON standings payload (NOT NULL)
     * @param createdAt       creation timestamp (may be null; DB sets default)
     */
    public RoundSnapshot(UUID id, UUID tenantId, UUID tournamentId, UUID phaseId,
                          int lapNumber, String snapshotPayload,
                          LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.tournamentId = tournamentId;
        this.phaseId = phaseId;
        this.lapNumber = lapNumber;
        this.snapshotPayload = snapshotPayload;
        this.createdAt = createdAt;
    }

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getTournamentId() { return tournamentId; }
    public void setTournamentId(UUID tournamentId) { this.tournamentId = tournamentId; }

    public UUID getPhaseId() { return phaseId; }
    public void setPhaseId(UUID phaseId) { this.phaseId = phaseId; }

    public int getLapNumber() { return lapNumber; }
    public void setLapNumber(int lapNumber) { this.lapNumber = lapNumber; }

    public String getSnapshotPayload() { return snapshotPayload; }
    public void setSnapshotPayload(String snapshotPayload) { this.snapshotPayload = snapshotPayload; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    @Override
    public String toString() {
        return "RoundSnapshot{id=" + id
                + ", tournamentId=" + tournamentId
                + ", phaseId=" + phaseId
                + ", lapNumber=" + lapNumber
                + ", createdAt=" + createdAt + '}';
    }
}
