package de.vvwt.tm.domain;

import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Spring Data JDBC entity for the {@code team} table.
 *
 * <p>A {@code Team} is tournament-scoped per D-20 (legacy parity). It represents a participating
 * team and carries several flags that control tournament behavior:
 *
 * <ul>
 *   <li>{@code participate} — whether the team is actively participating (default: true)
 *   <li>{@code refereeAssignment} — whether this team provides a referee (D-28)
 *   <li>{@code withoutAssessment} — if true, this team is excluded from standings/rankings and
 *       sorts last (D-26 {@code withoutassessment})
 * </ul>
 *
 * <p>The {@code teamNumber} is a human-readable label (1, 2, 3, ...) per legacy convention. Users
 * refer to teams by number. The unique constraint on {@code (tournamentId, teamNumber)} ensures
 * numbers are unique within a tournament.
 *
 * <p>The {@code referee_team_id} column on the {@code match} table (linking a team to a match as
 * referee) is introduced in E03S02, not here.
 *
 * @see Tournament
 * @see <a
 *     href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S01.story.md">Story
 *     E03S01</a>
 */
@Table("team")
public class Team {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every team belongs to exactly one tenant. Foreign key
     * references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Parent tournament — NOT NULL per D-20. Teams are tournament-scoped. Foreign key references
     * {@code tournament(id)}.
     */
    private UUID tournamentId;

    /**
     * Human-readable team identifier within this tournament (legacy parity). Together with {@code
     * tournamentId}, forms a unique pair (schema UNIQUE constraint).
     */
    private int teamNumber;

    /** Human-readable team name or label. */
    private String description;

    /**
     * Whether this team is actively participating in the tournament. Defaults to {@code true}. A
     * non-participating team may be registered but excluded from match generation.
     */
    private boolean participate;

    /**
     * Whether this team provides a referee for matches where it is not playing (D-28). Defaults to
     * {@code false}.
     */
    private boolean refereeAssignment;

    /**
     * If {@code true}, this team is excluded from normal standing calculations and always appears
     * last in rankings (D-26 {@code withoutassessment}, legacy parity). Defaults to {@code false}.
     */
    private boolean withoutAssessment;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Team() {}

    /**
     * Full constructor for programmatic creation.
     *
     * @param id primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId tenant scope (NOT NULL)
     * @param tournamentId parent tournament (NOT NULL)
     * @param teamNumber human-readable team number (unique within tournament)
     * @param description team name/label (NOT NULL)
     * @param participate whether the team participates (default: true)
     * @param refereeAssignment whether the team provides a referee (default: false)
     * @param withoutAssessment whether the team is excluded from standings (default: false)
     * @param createdAt creation timestamp (may be null; DB sets default)
     */
    public Team(
            UUID id,
            UUID tenantId,
            UUID tournamentId,
            int teamNumber,
            String description,
            boolean participate,
            boolean refereeAssignment,
            boolean withoutAssessment,
            LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.tournamentId = tournamentId;
        this.teamNumber = teamNumber;
        this.description = description;
        this.participate = participate;
        this.refereeAssignment = refereeAssignment;
        this.withoutAssessment = withoutAssessment;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public void setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
    }

    public UUID getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(UUID tournamentId) {
        this.tournamentId = tournamentId;
    }

    public int getTeamNumber() {
        return teamNumber;
    }

    public void setTeamNumber(int teamNumber) {
        this.teamNumber = teamNumber;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isParticipate() {
        return participate;
    }

    public void setParticipate(boolean participate) {
        this.participate = participate;
    }

    public boolean isRefereeAssignment() {
        return refereeAssignment;
    }

    public void setRefereeAssignment(boolean refereeAssignment) {
        this.refereeAssignment = refereeAssignment;
    }

    public boolean isWithoutAssessment() {
        return withoutAssessment;
    }

    public void setWithoutAssessment(boolean withoutAssessment) {
        this.withoutAssessment = withoutAssessment;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
