package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.ReadOnlyProperty;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code team_avatar} table.
 *
 * <p>A {@code TeamAvatar} is the structural identity of a team's position in a specific phase's
 * group layout. It is the key concept from DEC-9: within the slot-optimization service, teams
 * are represented exclusively by the tuple {@code (phaseId, groupNumber, groupPosition)}.
 * UUIDs never cross the optimizer service boundary.
 *
 * <p>A single team may have multiple avatars — one per phase it appears in. This is the
 * tournament-manager-side record that maps a structural position to a concrete team.
 *
 * <p>The schema enforces the DEC-9 structural identity via a UNIQUE constraint on
 * {@code (tournament_id, phase_id, group_number, group_position)}. This ensures that every
 * structural slot in a phase is occupied by at most one team avatar.
 *
 * <p>The {@code description} column is nullable and holds a human-readable label such as
 * {@code "Gruppe A, Platz 1"} for display purposes.
 *
 * @see Phase
 * @see Team
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S01.story.md">Story E03S01</a>
 */
@Table("team_avatar")
public class TeamAvatar {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every team avatar belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /**
     * Parent tournament — NOT NULL. Foreign key references {@code tournament(id)}.
     * Redundant with the phase FK, but included for direct tenant-scoped tournament queries.
     */
    private UUID tournamentId;

    /**
     * Parent phase — NOT NULL. Foreign key references {@code phase(id)}.
     * Together with {@code groupNumber} and {@code groupPosition}, forms the DEC-9 structural
     * identity tuple.
     */
    private UUID phaseId;

    /**
     * Group number within the phase (1-indexed). Part of the DEC-9 structural identity.
     * Corresponds to the legacy {@code groupNumber} in {@code MatchEntry.getTeam().getGroup()}.
     */
    private int groupNumber;

    /**
     * Position within the group (1-indexed). Part of the DEC-9 structural identity.
     * Corresponds to the legacy {@code groupPosition} in {@code MatchEntry.getTeam().getPosition()}.
     */
    private int groupPosition;

    /**
     * The concrete team occupying this structural slot — NOT NULL.
     * Foreign key references {@code team(id)}.
     * This is the only place in the tournament-manager data model that links structural
     * position to team identity.
     */
    private UUID teamId;

    /**
     * Optional human-readable label for this avatar (e.g., {@code "Gruppe A, Platz 1"}).
     * Nullable — the system generates this for display; it is not required for correctness.
     */
    private String description;

    /**
     * Row creation timestamp — set by the database via {@code DEFAULT CURRENT_TIMESTAMP}.
     * Marked {@link ReadOnlyProperty} so Spring Data JDBC never includes this column in
     * {@code INSERT} or {@code UPDATE} statements; the DB default applies on insert.
     */
    @ReadOnlyProperty
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public TeamAvatar() {
    }

    /**
     * Full constructor for programmatic creation.
     *
     * @param id            primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId      tenant scope (NOT NULL)
     * @param tournamentId  parent tournament (NOT NULL)
     * @param phaseId       parent phase (NOT NULL) — part of DEC-9 structural identity
     * @param groupNumber   group within the phase (part of DEC-9 structural identity)
     * @param groupPosition seat within the group (part of DEC-9 structural identity)
     * @param teamId        concrete team occupying this slot (NOT NULL)
     * @param description   optional human-readable label (may be null)
     * @param createdAt     creation timestamp (may be null; DB sets default)
     */
    public TeamAvatar(UUID id, UUID tenantId, UUID tournamentId, UUID phaseId,
                      int groupNumber, int groupPosition, UUID teamId,
                      String description, LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.tournamentId = tournamentId;
        this.phaseId = phaseId;
        this.groupNumber = groupNumber;
        this.groupPosition = groupPosition;
        this.teamId = teamId;
        this.description = description;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public UUID getTournamentId() { return tournamentId; }
    public void setTournamentId(UUID tournamentId) { this.tournamentId = tournamentId; }

    public UUID getPhaseId() { return phaseId; }
    public void setPhaseId(UUID phaseId) { this.phaseId = phaseId; }

    public int getGroupNumber() { return groupNumber; }
    public void setGroupNumber(int groupNumber) { this.groupNumber = groupNumber; }

    public int getGroupPosition() { return groupPosition; }
    public void setGroupPosition(int groupPosition) { this.groupPosition = groupPosition; }

    public UUID getTeamId() { return teamId; }
    public void setTeamId(UUID teamId) { this.teamId = teamId; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
