package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code tournament} table.
 *
 * <p>The {@code tournament} table is the root aggregate of the tournament domain. Each row
 * represents one tournament scoped to a tenant (DEC-5, DEC-17). The three Strategy columns
 * ({@code scoringRuleId}, {@code setValidationRuleId}, {@code matchGeneratorId}) store Spring
 * bean ids that are resolved at runtime by the respective service layer (D-15, D-16, D-27).
 *
 * <p>The {@code matchFormat} column stores the enum name as a VARCHAR (e.g., {@code BEST_OF_3}).
 * Mapping to the {@code MatchFormat} enum is introduced in E03S06.
 *
 * <p>The {@code status} column stores tournament lifecycle state:
 * <ul>
 *   <li>{@code DRAFT}     — created; teams are being registered</li>
 *   <li>{@code ACTIVE}    — at least one phase is in progress</li>
 *   <li>{@code COMPLETED} — all phases have completed</li>
 *   <li>{@code CANCELLED} — organizer cancelled the tournament</li>
 * </ul>
 *
 * <p>DEC-5 active-tournament invariant: at most one ACTIVE tournament exists per tenant at any
 * time. This is enforced at the schema level by the generated {@code active_sentinel} column and
 * its unique index in {@code V2__e03_core_schema.sql}.
 *
 * <p>The {@code active_sentinel} generated column is NOT mapped here — it is a database-side
 * computed column for constraint enforcement only; the application never writes or reads it
 * directly.
 *
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S01.story.md">Story E03S01</a>
 */
@Table("tournament")
public class Tournament {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every tournament belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /** Human-readable tournament label (e.g., "VVW Hallenturnier 2026"). */
    private String description;

    /**
     * Match format for all matches in this tournament. Stored as the enum name (VARCHAR).
     * Valid values: {@code BEST_OF_1}, {@code BEST_OF_3}, {@code BEST_OF_5}, {@code BEST_OF_7},
     * {@code FIXED_2_SETS}. Enum type is introduced in E03S06.
     */
    private String matchFormat;

    /** Spring bean id of the {@code ScoringRule} implementation to use (D-15). */
    private String scoringRuleId;

    /** Spring bean id of the {@code SetValidationRule} implementation to use (D-16). */
    private String setValidationRuleId;

    /** Spring bean id of the {@code MatchGenerator} implementation to use (D-27). */
    private String matchGeneratorId;

    /**
     * Tournament lifecycle status. Defaults to {@code DRAFT} at the schema level.
     * Valid values: {@code DRAFT}, {@code ACTIVE}, {@code COMPLETED}, {@code CANCELLED}.
     */
    private String status;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Tournament() {
    }

    /**
     * Full constructor for programmatic creation.
     *
     * @param id                    primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId              tenant scope (NOT NULL)
     * @param description           human-readable label (NOT NULL)
     * @param matchFormat           match format enum name (NOT NULL)
     * @param scoringRuleId         Spring bean id for scoring rule (NOT NULL)
     * @param setValidationRuleId   Spring bean id for set validation rule (NOT NULL)
     * @param matchGeneratorId      Spring bean id for match generator (NOT NULL)
     * @param status                lifecycle status (NOT NULL)
     * @param createdAt             creation timestamp (may be null; DB sets default)
     */
    public Tournament(UUID id, UUID tenantId, String description, String matchFormat,
                      String scoringRuleId, String setValidationRuleId, String matchGeneratorId,
                      String status, LocalDateTime createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.description = description;
        this.matchFormat = matchFormat;
        this.scoringRuleId = scoringRuleId;
        this.setValidationRuleId = setValidationRuleId;
        this.matchGeneratorId = matchGeneratorId;
        this.status = status;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getMatchFormat() { return matchFormat; }
    public void setMatchFormat(String matchFormat) { this.matchFormat = matchFormat; }

    public String getScoringRuleId() { return scoringRuleId; }
    public void setScoringRuleId(String scoringRuleId) { this.scoringRuleId = scoringRuleId; }

    public String getSetValidationRuleId() { return setValidationRuleId; }
    public void setSetValidationRuleId(String setValidationRuleId) { this.setValidationRuleId = setValidationRuleId; }

    public String getMatchGeneratorId() { return matchGeneratorId; }
    public void setMatchGeneratorId(String matchGeneratorId) { this.matchGeneratorId = matchGeneratorId; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
