package de.vvwt.tm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.UUID;

/**
 * Spring Data JDBC entity for the {@code tournament} table.
 *
 * <p>The {@code tournament} table is the root aggregate of the tournament domain. Each row
 * represents one tournament scoped to a tenant (DEC-5, DEC-17). The three Strategy columns
 * ({@code scoringRuleId}, {@code setValidationRuleId}, {@code matchGeneratorId}) store Spring
 * bean ids that are resolved at runtime by the respective service layer (D-15, D-16, D-27).
 *
 * <p>The {@code matchFormat} column stores the enum name as a VARCHAR (e.g., {@code BEST_OF_3}).
 * Mapping to the {@code MatchFormat} enum is introduced in E03S06.
 *
 * <p>The {@code status} column stores tournament lifecycle state:
 * <ul>
 *   <li>{@code DRAFT}     — created; teams are being registered</li>
 *   <li>{@code ACTIVE}    — at least one phase is in progress</li>
 *   <li>{@code COMPLETED} — all phases have completed</li>
 *   <li>{@code CANCELLED} — organizer cancelled the tournament</li>
 * </ul>
 *
 * <p>DEC-5 active-tournament invariant: at most one ACTIVE tournament exists per tenant at any
 * time. This is enforced at the schema level by the generated {@code active_sentinel} column and
 * its unique index in {@code V2__e03_core_schema.sql}.
 *
 * <p>The {@code active_sentinel} generated column is NOT mapped here — it is a database-side
 * computed column for constraint enforcement only; the application never writes or reads it
 * directly.
 *
 * <p>E05S04 additions: {@code appointment} (optional tournament date), {@code fieldCount}
 * (court count, ≥1), {@code teamCount} (team count, ≥2) added via V7 migration. These fields
 * complete the tournament creation form required by the admin UI.
 *
 * <p>E08S01 addition: {@code plannedStartTime} (optional time-of-day for print timeline calculation)
 * added via V11 migration. Nullable — tournaments without print output do not require it.
 *
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E03S01.story.md">Story E03S01</a>
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E05S04.story.md">Story E05S04</a>
 * @see <a href="../../../../../../../../.gaai/project/contexts/artefacts/stories/E08S01.story.md">Story E08S01</a>
 */
@Table("tournament")
public class Tournament {

    /** Primary key — UUID generated by the application layer before insert. */
    @Id
    private UUID id;

    /**
     * Tenant scope — NOT NULL per DEC-17. Every tournament belongs to exactly one tenant.
     * Foreign key references {@code tenants(id)}.
     */
    private UUID tenantId;

    /** Human-readable tournament label (e.g., "VVW Hallenturnier 2026"). */
    private String description;

    /**
     * Match format for all matches in this tournament. Stored as the enum name (VARCHAR).
     * Valid values: {@code BEST_OF_1}, {@code BEST_OF_3}, {@code BEST_OF_5}, {@code BEST_OF_7},
     * {@code FIXED_2_SETS}. Enum type is introduced in E03S06.
     */
    private String matchFormat;

    /** Spring bean id of the {@code ScoringRule} implementation to use (D-15). */
    private String scoringRuleId;

    /** Spring bean id of the {@code SetValidationRule} implementation to use (D-16). */
    private String setValidationRuleId;

    /** Spring bean id of the {@code MatchGenerator} implementation to use (D-27). */
    private String matchGeneratorId;

    /**
     * Tournament lifecycle status. Defaults to {@code DRAFT} at the schema level.
     * Valid values: {@code DRAFT}, {@code ACTIVE}, {@code COMPLETED}, {@code CANCELLED}.
     */
    private String status;

    /** Row creation timestamp — set by the database via DEFAULT CURRENT_TIMESTAMP. */
    private LocalDateTime createdAt;

    /**
     * Optional tournament appointment date/time (AC1, AC3 — E05S04).
     * May be {@code null} if the organizer has not yet set a date.
     */
    private LocalDateTime appointment;

    /**
     * Number of courts (fields) available for this tournament (AC1, AC3 — E05S04).
     * Must be ≥ 1; validated at the service layer.
     */
    @Column("field_count")
    private int fieldCount;

    /**
     * Number of teams participating in this tournament (AC1, AC3 — E05S04).
     * Must be ≥ 2; validated at the service layer.
     */
    @Column("team_count")
    private int teamCount;

    /**
     * Optional planned start time for the tournament (AC1 — E08S01).
     * Time-of-day only — no date component. Nullable: tournaments without print output
     * do not require a start time. Used by the timeline calculation service (E08S03) to
     * compute predicted round times for the Laufzettel print output.
     */
    @Column("planned_start_time")
    private LocalTime plannedStartTime;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default constructor required by Spring Data JDBC. */
    public Tournament() {
    }

    /**
     * Full constructor for programmatic creation (legacy — no appointment/fieldCount/teamCount).
     *
     * @param id                    primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId              tenant scope (NOT NULL)
     * @param description           human-readable label (NOT NULL)
     * @param matchFormat           match format enum name (NOT NULL)
     * @param scoringRuleId         Spring bean id for scoring rule (NOT NULL)
     * @param setValidationRuleId   Spring bean id for set validation rule (NOT NULL)
     * @param matchGeneratorId      Spring bean id for match generator (NOT NULL)
     * @param status                lifecycle status (NOT NULL)
     * @param createdAt             creation timestamp (may be null; DB sets default)
     */
    public Tournament(UUID id, UUID tenantId, String description, String matchFormat,
                      String scoringRuleId, String setValidationRuleId, String matchGeneratorId,
                      String status, LocalDateTime createdAt) {
        this(id, tenantId, description, matchFormat, scoringRuleId, setValidationRuleId,
                matchGeneratorId, status, createdAt, null, 1, 2);
    }

    /**
     * Full constructor for programmatic creation (E05S04 — includes appointment, fieldCount, teamCount).
     *
     * @param id                    primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId              tenant scope (NOT NULL)
     * @param description           human-readable label (NOT NULL)
     * @param matchFormat           match format enum name (NOT NULL)
     * @param scoringRuleId         Spring bean id for scoring rule (NOT NULL)
     * @param setValidationRuleId   Spring bean id for set validation rule (NOT NULL)
     * @param matchGeneratorId      Spring bean id for match generator (NOT NULL)
     * @param status                lifecycle status (NOT NULL)
     * @param createdAt             creation timestamp (may be null; DB sets default)
     * @param appointment           optional tournament date (may be null)
     * @param fieldCount            court count (≥ 1)
     * @param teamCount             team count (≥ 2)
     */
    public Tournament(UUID id, UUID tenantId, String description, String matchFormat,
                      String scoringRuleId, String setValidationRuleId, String matchGeneratorId,
                      String status, LocalDateTime createdAt, LocalDateTime appointment,
                      int fieldCount, int teamCount) {
        this(id, tenantId, description, matchFormat, scoringRuleId, setValidationRuleId,
                matchGeneratorId, status, createdAt, appointment, fieldCount, teamCount, null);
    }

    /**
     * Full constructor for programmatic creation (E08S01 — includes plannedStartTime).
     *
     * @param id                    primary key (generated by caller via {@code UUID.randomUUID()})
     * @param tenantId              tenant scope (NOT NULL)
     * @param description           human-readable label (NOT NULL)
     * @param matchFormat           match format enum name (NOT NULL)
     * @param scoringRuleId         Spring bean id for scoring rule (NOT NULL)
     * @param setValidationRuleId   Spring bean id for set validation rule (NOT NULL)
     * @param matchGeneratorId      Spring bean id for match generator (NOT NULL)
     * @param status                lifecycle status (NOT NULL)
     * @param createdAt             creation timestamp (may be null; DB sets default)
     * @param appointment           optional tournament date (may be null)
     * @param fieldCount            court count (≥ 1)
     * @param teamCount             team count (≥ 2)
     * @param plannedStartTime      optional time-of-day for print timeline (may be null)
     */
    public Tournament(UUID id, UUID tenantId, String description, String matchFormat,
                      String scoringRuleId, String setValidationRuleId, String matchGeneratorId,
                      String status, LocalDateTime createdAt, LocalDateTime appointment,
                      int fieldCount, int teamCount, LocalTime plannedStartTime) {
        this.id = id;
        this.tenantId = tenantId;
        this.description = description;
        this.matchFormat = matchFormat;
        this.scoringRuleId = scoringRuleId;
        this.setValidationRuleId = setValidationRuleId;
        this.matchGeneratorId = matchGeneratorId;
        this.status = status;
        this.createdAt = createdAt;
        this.appointment = appointment;
        this.fieldCount = fieldCount;
        this.teamCount = teamCount;
        this.plannedStartTime = plannedStartTime;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getTenantId() { return tenantId; }
    public void setTenantId(UUID tenantId) { this.tenantId = tenantId; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getMatchFormat() { return matchFormat; }
    public void setMatchFormat(String matchFormat) { this.matchFormat = matchFormat; }

    public String getScoringRuleId() { return scoringRuleId; }
    public void setScoringRuleId(String scoringRuleId) { this.scoringRuleId = scoringRuleId; }

    public String getSetValidationRuleId() { return setValidationRuleId; }
    public void setSetValidationRuleId(String setValidationRuleId) { this.setValidationRuleId = setValidationRuleId; }

    public String getMatchGeneratorId() { return matchGeneratorId; }
    public void setMatchGeneratorId(String matchGeneratorId) { this.matchGeneratorId = matchGeneratorId; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getAppointment() { return appointment; }
    public void setAppointment(LocalDateTime appointment) { this.appointment = appointment; }

    public int getFieldCount() { return fieldCount; }
    public void setFieldCount(int fieldCount) { this.fieldCount = fieldCount; }

    public int getTeamCount() { return teamCount; }
    public void setTeamCount(int teamCount) { this.teamCount = teamCount; }

    public LocalTime getPlannedStartTime() { return plannedStartTime; }
    public void setPlannedStartTime(LocalTime plannedStartTime) { this.plannedStartTime = plannedStartTime; }
}
