-- ============================================================
-- V16__e14s08_device_location_nullable.sql — Drop NOT NULL on devices.location_id
-- Story:  E14S08
-- DECs:   DEC-24 (device post-registration location assignment)
--         DEC-17 (2026-04-18 amendment: device-model carve-out from eager NOT NULL rule)
--         DEC-14 (H2 + Flyway persistence)
-- ============================================================
--
-- Context:
--   DEC-24 resolves the E14S07 planning block by establishing that device registration
--   does NOT require a location at creation time. Devices are registered first (tenant
--   context only) and then assigned to a location via a separate admin action.
--
--   V8 (E06S03) originally defined devices.location_id as NOT NULL. This migration
--   performs a forward-rolling change to drop that constraint. V8 is NOT rewritten —
--   migration history is preserved per DEC-14 / DEC-17 norms.
--
--   After this migration, NULL in devices.location_id means "registered, not yet
--   assigned to a location". All other location-scoped entities retain NOT NULL.
--
-- H2 DDL syntax note:
--   H2 2.x supports both:
--     ALTER TABLE devices ALTER COLUMN location_id SET NULL
--     ALTER TABLE devices ALTER COLUMN location_id DROP NOT NULL
--   Both forms drop the NOT NULL constraint. We use DROP NOT NULL as it is more
--   explicit about the intent (removing a constraint, not changing a default).
--   Tested against H2 2.3.x (Spring Boot 4.0.5 BOM).
--
-- Scope: ONLY devices.location_id. No other column changes in this migration.
-- ============================================================

ALTER TABLE devices ALTER COLUMN location_id DROP NOT NULL;
